public class Control_Monad {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object whenM = (java.util.function.Function<Object, Object>) (dictMonad_0) -> ((new java.util.function.Supplier<Object>() { Object Bind1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((new java.util.function.Supplier<Object>() { Object Applicative0_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (mb_3) -> (java.util.function.Function<Object, Object>) (m_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_1).get("bind"))).apply(mb_3))).apply((java.util.function.Function<Object, Object>) (b_5) -> ( ((Boolean) (b_5)) ? m_4 : ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Applicative0_2).get("pure"))).apply(Data_Unit.unit))); } })).get(); } })).get();
public static final Object unlessM = (java.util.function.Function<Object, Object>) (dictMonad_0) -> ((new java.util.function.Supplier<Object>() { Object Bind1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((new java.util.function.Supplier<Object>() { Object Applicative0_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (mb_3) -> (java.util.function.Function<Object, Object>) (m_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_1).get("bind"))).apply(mb_3))).apply((java.util.function.Function<Object, Object>) (b_5) -> ( ((Boolean) (!(((Boolean) (b_5))))) ? m_4 : ( ((Boolean) (b_5)) ? ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Applicative0_2).get("pure"))).apply(Data_Unit.unit) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); } })).get(); } })).get();
public static final Object monadProxy = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Applicative.applicativeProxy); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Bind.bindProxy); }};
public static final Object monadFn = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Applicative.applicativeFn); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Bind.bindFn); }};
public static final Object monadArray = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Applicative.applicativeArray); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Bind.bindArray); }};
public static final Object liftM1 = (java.util.function.Function<Object, Object>) (dictMonad_0) -> ((new java.util.function.Supplier<Object>() { Object Bind1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((new java.util.function.Supplier<Object>() { Object Applicative0_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (f_3) -> (java.util.function.Function<Object, Object>) (a_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_1).get("bind"))).apply(a_4))).apply((java.util.function.Function<Object, Object>) (a_prime__5) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Applicative0_2).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_3)).apply(a_prime__5))); } })).get(); } })).get();
public static final Object ap = (java.util.function.Function<Object, Object>) (dictMonad_0) -> ((new java.util.function.Supplier<Object>() { Object Bind1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Bind1"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((new java.util.function.Supplier<Object>() { Object Applicative0_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonad_0).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (f_3) -> (java.util.function.Function<Object, Object>) (a_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_1).get("bind"))).apply(f_3))).apply((java.util.function.Function<Object, Object>) (f_prime__5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_1).get("bind"))).apply(a_4))).apply((java.util.function.Function<Object, Object>) (a_prime__6) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Applicative0_2).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_prime__5)).apply(a_prime__6)))); } })).get(); } })).get();
}
