public class Control_Apply {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object arrayApply = FFI_STUB;
    public static Object arrayApply(Object... args) { return null; }

public static final Object applyProxy = new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> new Type_Proxy.Proxy()); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Functor.functorProxy); }};
public static final Object applyFn = new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (g_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (f_0)).apply(x_2))).apply(((java.util.function.Function<Object, Object>) (g_1)).apply(x_2))); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Functor.functorFn); }};
public static final Object applyArray = new java.util.LinkedHashMap<String, Object>() {{ put("apply", Control_Apply.arrayApply); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Functor.functorArray); }};
public static final Object apply = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("apply");
public static final Object applyFirst = (java.util.function.Function<Object, Object>) (dictApply_0) -> ((new java.util.function.Supplier<Object>() { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (a_2) -> (java.util.function.Function<Object, Object>) (b_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Functor0_1).get("map"))).apply(Data_Function.$const))).apply(a_2)))).apply(b_3); } })).get();
public static final Object applySecond = (java.util.function.Function<Object, Object>) (dictApply_0) -> ((new java.util.function.Supplier<Object>() { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (a_2) -> (java.util.function.Function<Object, Object>) (b_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Functor0_1).get("map"))).apply((java.util.function.Function<Object, Object>) (v_4) -> (java.util.function.Function<Object, Object>) (x_5) -> x_5))).apply(a_2)))).apply(b_3); } })).get();
public static final Object lift2 = (java.util.function.Function<Object, Object>) (dictApply_0) -> ((new java.util.function.Supplier<Object>() { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (b_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Functor0_1).get("map"))).apply(f_2))).apply(a_3)))).apply(b_4); } })).get();
public static final Object lift3 = (java.util.function.Function<Object, Object>) (dictApply_0) -> ((new java.util.function.Supplier<Object>() { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (b_4) -> (java.util.function.Function<Object, Object>) (c_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Functor0_1).get("map"))).apply(f_2))).apply(a_3)))).apply(b_4)))).apply(c_5); } })).get();
public static final Object lift4 = (java.util.function.Function<Object, Object>) (dictApply_0) -> ((new java.util.function.Supplier<Object>() { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (b_4) -> (java.util.function.Function<Object, Object>) (c_5) -> (java.util.function.Function<Object, Object>) (d_6) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Functor0_1).get("map"))).apply(f_2))).apply(a_3)))).apply(b_4)))).apply(c_5)))).apply(d_6); } })).get();
public static final Object lift5 = (java.util.function.Function<Object, Object>) (dictApply_0) -> ((new java.util.function.Supplier<Object>() { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (a_3) -> (java.util.function.Function<Object, Object>) (b_4) -> (java.util.function.Function<Object, Object>) (c_5) -> (java.util.function.Function<Object, Object>) (d_6) -> (java.util.function.Function<Object, Object>) (e_7) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Functor0_1).get("map"))).apply(f_2))).apply(a_3)))).apply(b_4)))).apply(c_5)))).apply(d_6)))).apply(e_7); } })).get();
}
