public class Control_Applicative {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object pure = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("pure");
public static final Object unless = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ( ((Boolean) (!(((Boolean) (v_1))))) ? v1_2 : ( ((Boolean) (v_1)) ? ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0).get("pure"))).apply(Data_Unit.unit) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()));
public static final Object when = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ( ((Boolean) (v_1)) ? v1_2 : ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0).get("pure"))).apply(Data_Unit.unit));
public static final Object liftA1 = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> ((new java.util.function.Supplier<Object>() { Object Apply0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0).get("Apply0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (a_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Apply0_1).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0).get("pure"))).apply(f_2)))).apply(a_3); } })).get();
public static final Object applicativeProxy = new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (v_0) -> new Type_Proxy.Proxy()); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Apply.applyProxy); }};
public static final Object applicativeFn = new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (x_0) -> (java.util.function.Function<Object, Object>) (v_1) -> x_0); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Apply.applyFn); }};
public static final Object applicativeArray = new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (x_0) -> new Object[]{x_0}); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Control_Apply.applyArray); }};
}
