public class Data_String_NonEmpty_Internal {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object NonEmptyString = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object NonEmptyReplacement = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object toUpper = (java.util.function.Function<Object, Object>) (v_0) -> ((java.util.function.Function<Object, Object>) (Data_String_Common.toUpper)).apply(v_0);
public static final Object toString = (java.util.function.Function<Object, Object>) (v_0) -> v_0;
public static final Object toLower = (java.util.function.Function<Object, Object>) (v_0) -> ((java.util.function.Function<Object, Object>) (Data_String_Common.toLower)).apply(v_0);
public static final Object showNonEmptyString = new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_0) -> (((String) ((((String) ("(NonEmptyString.unsafeFromString ")) + ((String) (((java.util.function.Function<Object, Object>) (Data_Show.showStringImpl)).apply(v_0)))))) + ((String) (")")))); }};
public static final Object showNonEmptyReplacement = new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_0) -> (((String) ((((String) ("(NonEmptyReplacement (NonEmptyString.unsafeFromString ")) + ((String) (((java.util.function.Function<Object, Object>) (Data_Show.showStringImpl)).apply(v_0)))))) + ((String) ("))")))); }};
public static final Object semigroupNonEmptyString = Data_Semigroup.semigroupString;
public static final Object semigroupNonEmptyReplacement = Data_Semigroup.semigroupString;
public static final Object replaceAll = (java.util.function.Function<Object, Object>) (pat_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_Common.replaceAll)).apply(pat_0))).apply(v_1))).apply(v1_2);
public static final Object replace = (java.util.function.Function<Object, Object>) (pat_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_Common.replace)).apply(pat_0))).apply(v_1))).apply(v1_2);
public static final Object prependString = (java.util.function.Function<Object, Object>) (s1_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (((String) (s1_0)) + ((String) (v_1)));
public static final Object ordNonEmptyString = Data_Ord.ordString;
public static final Object ordNonEmptyReplacement = Data_Ord.ordString;
public static final Object nonEmptyNonEmpty = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("nes", (java.util.function.Function<Object, Object>) (p_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(p_1)); }};
public static final Object nes = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("nes");
public static final Object makeNonEmptyBad = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("nes", (java.util.function.Function<Object, Object>) (v_1) -> ""); }};
public static final Object localeCompare = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_Common.localeCompare)).apply(v_0))).apply(v1_1);
public static final Object liftS = (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> ((java.util.function.Function<Object, Object>) (f_0)).apply(v_1);
public static final Object startsWith = (java.util.function.Function<Object, Object>) (x_0) -> (java.util.function.Function<Object, Object>) (v_1) -> ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.stripPrefix)).apply(x_0))).apply(v_1); public Object get() { return ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Nothing))) ? false : ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Just))) ? true : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); } })).get();
public static final Object joinWith1 = (java.util.function.Function<Object, Object>) (dictFoldable1_0) -> ((new java.util.function.Supplier<Object>() { Object Foldable0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFoldable1_0).get("Foldable0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (x_3) -> ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Foldable0_1).get("foldl"))).apply((java.util.function.Function<Object, Object>) (v_4) -> (java.util.function.Function<Object, Object>) (v1_5) -> ( ((Boolean) (((java.util.LinkedHashMap<String, Object>) v_4).get("init"))) ? new java.util.LinkedHashMap<String, Object>() {{ put("init", false); put("acc", v1_5); }} : new java.util.LinkedHashMap<String, Object>() {{ put("init", false); put("acc", (((String) ((((String) (((java.util.LinkedHashMap<String, Object>) v_4).get("acc"))) + ((String) (v_2))))) + ((String) (v1_5)))); }})))).apply(new java.util.LinkedHashMap<String, Object>() {{ put("init", true); put("acc", ""); }}))).apply(x_3)).get("acc"); } })).get();
public static final Object joinWith = (java.util.function.Function<Object, Object>) (dictFoldable_0) -> (java.util.function.Function<Object, Object>) (splice_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFoldable_0).get("foldl"))).apply((java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (v1_4) -> ( ((Boolean) (((java.util.LinkedHashMap<String, Object>) v_3).get("init"))) ? new java.util.LinkedHashMap<String, Object>() {{ put("init", false); put("acc", v1_4); }} : new java.util.LinkedHashMap<String, Object>() {{ put("init", false); put("acc", (((String) ((((String) (((java.util.LinkedHashMap<String, Object>) v_3).get("acc"))) + ((String) (splice_1))))) + ((String) (v1_4)))); }})))).apply(new java.util.LinkedHashMap<String, Object>() {{ put("init", true); put("acc", ""); }}))).apply(x_2)).get("acc");
public static final Object join1With = (java.util.function.Function<Object, Object>) (dictFoldable1_0) -> ((new java.util.function.Supplier<Object>() { Object Foldable0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFoldable1_0).get("Foldable0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (splice_2) -> (java.util.function.Function<Object, Object>) (x_3) -> ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Foldable0_1).get("foldl"))).apply((java.util.function.Function<Object, Object>) (v_4) -> (java.util.function.Function<Object, Object>) (v1_5) -> ( ((Boolean) (((java.util.LinkedHashMap<String, Object>) v_4).get("init"))) ? new java.util.LinkedHashMap<String, Object>() {{ put("init", false); put("acc", v1_5); }} : new java.util.LinkedHashMap<String, Object>() {{ put("init", false); put("acc", (((String) ((((String) (((java.util.LinkedHashMap<String, Object>) v_4).get("acc"))) + ((String) (splice_2))))) + ((String) (v1_5)))); }})))).apply(new java.util.LinkedHashMap<String, Object>() {{ put("init", true); put("acc", ""); }}))).apply(x_3)).get("acc"); } })).get();
public static final Object fromString = (java.util.function.Function<Object, Object>) (v_0) -> ( ((Boolean) (java.util.Objects.equals(v_0, ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(v_0));
public static final Object stripPrefix = (java.util.function.Function<Object, Object>) (pat_0) -> (java.util.function.Function<Object, Object>) (a_1) -> ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.stripPrefix)).apply(pat_0))).apply(a_1); public Object get() { return ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Just))) ? ( ((Boolean) (java.util.Objects.equals((((Data_Maybe.Just) __local_var_2).value0), ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just((((Data_Maybe.Just) __local_var_2).value0))) : ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Nothing))) ? new Data_Maybe.Nothing() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); } })).get();
public static final Object stripSuffix = (java.util.function.Function<Object, Object>) (pat_0) -> (java.util.function.Function<Object, Object>) (a_1) -> ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.stripSuffix)).apply(pat_0))).apply(a_1); public Object get() { return ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Just))) ? ( ((Boolean) (java.util.Objects.equals((((Data_Maybe.Just) __local_var_2).value0), ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just((((Data_Maybe.Just) __local_var_2).value0))) : ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Nothing))) ? new Data_Maybe.Nothing() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); } })).get();
public static final Object trim = (java.util.function.Function<Object, Object>) (v_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Data_String_Common.trim)).apply(v_0); public Object get() { return ( ((Boolean) (java.util.Objects.equals(__local_var_1, ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(__local_var_1)); } })).get();
public static final Object unsafeFromString = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (x_1) -> ( ((Boolean) (java.util.Objects.equals(x_1, ""))) ? ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get() : x_1);
public static final Object eqNonEmptyString = Data_Eq.eqString;
public static final Object eqNonEmptyReplacement = Data_Eq.eqString;
public static final Object endsWith = (java.util.function.Function<Object, Object>) (x_0) -> (java.util.function.Function<Object, Object>) (v_1) -> ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.stripSuffix)).apply(x_0))).apply(v_1); public Object get() { return ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Nothing))) ? false : ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Just))) ? true : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); } })).get();
public static final Object contains = (java.util.function.Function<Object, Object>) (x_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.contains)).apply(x_0); public Object get() { return (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.function.Function<Object, Object>) (__local_var_1)).apply(v_2); } })).get();
public static final Object appendString = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (s2_1) -> (((String) (v_0)) + ((String) (s2_1)));
}
