public class Data_DivisionRing {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object recip = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("recip");
public static final Object rightDiv = (java.util.function.Function<Object, Object>) (dictDivisionRing_0) -> ((new java.util.function.Supplier<Object>() { Object Semiring0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivisionRing_0).get("Ring0"))).apply(null /* TODO: PrimUndefined */)).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (a_2) -> (java.util.function.Function<Object, Object>) (b_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Semiring0_1).get("mul"))).apply(a_2))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivisionRing_0).get("recip"))).apply(b_3)); } })).get();
public static final Object leftDiv = (java.util.function.Function<Object, Object>) (dictDivisionRing_0) -> ((new java.util.function.Supplier<Object>() { Object Semiring0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivisionRing_0).get("Ring0"))).apply(null /* TODO: PrimUndefined */)).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (a_2) -> (java.util.function.Function<Object, Object>) (b_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Semiring0_1).get("mul"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictDivisionRing_0).get("recip"))).apply(b_3)))).apply(a_2); } })).get();
public static final Object divisionringNumber = new java.util.LinkedHashMap<String, Object>() {{ put("recip", (java.util.function.Function<Object, Object>) (x_0) -> (((Double) (1.0)) / ((Double) (x_0)))); put("Ring0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Ring.ringNumber); }};
}
