public class Data_Maybe_First {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object First = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showFirst = (java.util.function.Function<Object, Object>) (dictShow_0) -> ((new java.util.function.Supplier<Object>() { Object showMaybe_1 = new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1) -> ( ((Boolean) ((v_1 instanceof Data_Maybe.Just))) ? (((String) ((((String) ("(Just ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply((((Data_Maybe.Just) v_1).value0))))))) + ((String) (")"))) : ( ((Boolean) ((v_1 instanceof Data_Maybe.Nothing))) ? "Nothing" : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }}; public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_2) -> (((String) ((((String) ("First (")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) showMaybe_1).get("show"))).apply(v_2)))))) + ((String) (")")))); }}; } })).get();
public static final Object semigroupFirst = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ( ((Boolean) ((v_0 instanceof Data_Maybe.Just))) ? v_0 : v1_1)); }};
public static final Object ordFirst = (java.util.function.Function<Object, Object>) (dictOrd_0) -> ((new java.util.function.Supplier<Object>() { Object eqMaybe1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_2) -> (java.util.function.Function<Object, Object>) (y_3) -> ( ((Boolean) ((x_2 instanceof Data_Maybe.Nothing))) ? (y_3 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_2 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_3 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("eq"))).apply((((Data_Maybe.Just) x_2).value0)))).apply((((Data_Maybe.Just) y_3).value0)))))))))); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (x_2) -> (java.util.function.Function<Object, Object>) (y_3) -> ( ((Boolean) ((x_2 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((y_3 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.EQ() : new Data_Ordering.LT()) : ( ((Boolean) ((y_3 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.GT() : ( ((Boolean) ((((Boolean) ((x_2 instanceof Data_Maybe.Just))) && ((Boolean) ((y_3 instanceof Data_Maybe.Just)))))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply((((Data_Maybe.Just) x_2).value0)))).apply((((Data_Maybe.Just) y_3).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> eqMaybe1_1); }}; } })).get();
public static final Object ord1First = Data_Maybe.ord1Maybe;
public static final Object newtypeFirst = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object monoidFirst = new java.util.LinkedHashMap<String, Object>() {{ put("mempty", new Data_Maybe.Nothing()); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe_First.semigroupFirst); }};
public static final Object monadFirst = Data_Maybe.monadMaybe;
public static final Object invariantFirst = Data_Maybe.invariantMaybe;
public static final Object functorFirst = Data_Maybe.functorMaybe;
public static final Object extendFirst = Data_Maybe.extendMaybe;
public static final Object eqFirst = (java.util.function.Function<Object, Object>) (dictEq_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_1) -> (java.util.function.Function<Object, Object>) (y_2) -> ( ((Boolean) ((x_1 instanceof Data_Maybe.Nothing))) ? (y_2 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_1 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_2 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq_0).get("eq"))).apply((((Data_Maybe.Just) x_1).value0)))).apply((((Data_Maybe.Just) y_2).value0)))))))))); }};
public static final Object eq1First = Data_Maybe.eq1Maybe;
public static final Object boundedFirst = (java.util.function.Function<Object, Object>) (dictBounded_0) -> ((new java.util.function.Supplier<Object>() { Object ordMaybe1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("Ord0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((new java.util.function.Supplier<Object>() { Object eqMaybe1_2 = ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("Eq0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_3) -> (java.util.function.Function<Object, Object>) (y_4) -> ( ((Boolean) ((x_3 instanceof Data_Maybe.Nothing))) ? (y_4 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_3 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_4 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("eq"))).apply((((Data_Maybe.Just) x_3).value0)))).apply((((Data_Maybe.Just) y_4).value0)))))))))); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (x_3) -> (java.util.function.Function<Object, Object>) (y_4) -> ( ((Boolean) ((x_3 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((y_4 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.EQ() : new Data_Ordering.LT()) : ( ((Boolean) ((y_4 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.GT() : ( ((Boolean) ((((Boolean) ((x_3 instanceof Data_Maybe.Just))) && ((Boolean) ((y_4 instanceof Data_Maybe.Just)))))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("compare"))).apply((((Data_Maybe.Just) x_3).value0)))).apply((((Data_Maybe.Just) y_4).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> eqMaybe1_2); }}; } })).get(); } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("top", new Data_Maybe.Just(((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("top"))); put("bottom", new Data_Maybe.Nothing()); put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> ordMaybe1_1); }}; } })).get();
public static final Object bindFirst = Data_Maybe.bindMaybe;
public static final Object applyFirst = Data_Maybe.applyMaybe;
public static final Object applicativeFirst = Data_Maybe.applicativeMaybe;
public static final Object altFirst = new java.util.LinkedHashMap<String, Object>() {{ put("alt", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ( ((Boolean) ((v_0 instanceof Data_Maybe.Just))) ? v_0 : v1_1)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe.functorMaybe); }};
public static final Object plusFirst = new java.util.LinkedHashMap<String, Object>() {{ put("empty", new Data_Maybe.Nothing()); put("Alt0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe_First.altFirst); }};
public static final Object alternativeFirst = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe.applicativeMaybe); put("Plus1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe_First.plusFirst); }};
}
