public class Data_Const {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Const = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showConst = (java.util.function.Function<Object, Object>) (dictShow_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1) -> (((String) ((((String) ("(Const ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")")))); }};
public static final Object semiringConst = (java.util.function.Function<Object, Object>) (dictSemiring_0) -> dictSemiring_0;
public static final Object semigroupoidConst = new java.util.LinkedHashMap<String, Object>() {{ put("compose", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> v1_1); }};
public static final Object semigroupConst = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> dictSemigroup_0;
public static final Object ringConst = (java.util.function.Function<Object, Object>) (dictRing_0) -> dictRing_0;
public static final Object ordConst = (java.util.function.Function<Object, Object>) (dictOrd_0) -> dictOrd_0;
public static final Object newtypeConst = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object monoidConst = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> dictMonoid_0;
public static final Object heytingAlgebraConst = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0) -> dictHeytingAlgebra_0;
public static final Object functorConst = new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (m_1) -> m_1); }};
public static final Object invariantConst = new java.util.LinkedHashMap<String, Object>() {{ put("imap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (m_2) -> m_2); }};
public static final Object euclideanRingConst = (java.util.function.Function<Object, Object>) (dictEuclideanRing_0) -> dictEuclideanRing_0;
public static final Object eqConst = (java.util.function.Function<Object, Object>) (dictEq_0) -> dictEq_0;
public static final Object eq1Const = (java.util.function.Function<Object, Object>) (dictEq_0) -> ((new java.util.function.Supplier<Object>() { Object eq_1 = ((java.util.LinkedHashMap<String, Object>) dictEq_0).get("eq"); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("eq1", (java.util.function.Function<Object, Object>) (dictEq1_2) -> eq_1); }}; } })).get();
public static final Object ord1Const = (java.util.function.Function<Object, Object>) (dictOrd_0) -> ((new java.util.function.Supplier<Object>() { Object compare_1 = ((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object eq1Const1_2 = ((new java.util.function.Supplier<Object>() { Object eq_2 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */)).get("eq"); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("eq1", (java.util.function.Function<Object, Object>) (dictEq1_3) -> eq_2); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compare1", (java.util.function.Function<Object, Object>) (dictOrd1_3) -> compare_1); put("Eq10", (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> eq1Const1_2); }}; } })).get(); } })).get();
public static final Object commutativeRingConst = (java.util.function.Function<Object, Object>) (dictCommutativeRing_0) -> dictCommutativeRing_0;
public static final Object boundedConst = (java.util.function.Function<Object, Object>) (dictBounded_0) -> dictBounded_0;
public static final Object booleanAlgebraConst = (java.util.function.Function<Object, Object>) (dictBooleanAlgebra_0) -> dictBooleanAlgebra_0;
public static final Object applyConst = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append"))).apply(v_1))).apply(v1_2)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> Data_Const.functorConst); }};
public static final Object applicativeConst = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object applyConst1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("append"))).apply(v_2))).apply(v1_3)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> Data_Const.functorConst); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("mempty")); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> applyConst1_1); }}; } })).get();
}
