public class Data_Bifunctor_Join {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Join = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showJoin = (java.util.function.Function<Object, Object>) (dictShow_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1) -> (((String) ((((String) ("(Join ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")")))); }};
public static final Object ordJoin = (java.util.function.Function<Object, Object>) (dictOrd_0) -> dictOrd_0;
public static final Object newtypeJoin = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object eqJoin = (java.util.function.Function<Object, Object>) (dictEq_0) -> dictEq_0;
public static final Object bifunctorJoin = (java.util.function.Function<Object, Object>) (dictBifunctor_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBifunctor_0).get("bimap"))).apply(f_1))).apply(f_1))).apply(v_2)); }};
public static final Object biapplyJoin = (java.util.function.Function<Object, Object>) (dictBiapply_0) -> ((new java.util.function.Supplier<Object>() { Object bifunctorJoin1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (v_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("bimap"))).apply(f_2))).apply(f_2))).apply(v_3)); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0).get("biapply"))).apply(v_2))).apply(v1_3)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> bifunctorJoin1_1); }}; } })).get();
public static final Object biapplicativeJoin = (java.util.function.Function<Object, Object>) (dictBiapplicative_0) -> ((new java.util.function.Supplier<Object>() { Object biapplyJoin1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapplicative_0).get("Biapply0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((new java.util.function.Supplier<Object>() { Object bifunctorJoin1_2 = ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_3) -> (java.util.function.Function<Object, Object>) (v_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("bimap"))).apply(f_3))).apply(f_3))).apply(v_4)); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (v1_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("biapply"))).apply(v_3))).apply(v1_4)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> bifunctorJoin1_2); }}; } })).get(); } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (a_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapplicative_0).get("bipure"))).apply(a_2))).apply(a_2)); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> biapplyJoin1_1); }}; } })).get();
}
