public class Data_Number_Approximate {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Tolerance = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object Fraction = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object eqRelative = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (java.util.function.Function<Object, Object>) (v2_2) -> ( ((Boolean) ((((Double) (v1_1)) == ((Double) (0.0))))) ? !(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordNumberImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(((java.util.function.Function<Object, Object>) (Data_Number.abs)).apply(v2_2)))).apply(v_0) instanceof Data_Ordering.GT)))) : ( ((Boolean) ((((Double) (v2_2)) == ((Double) (0.0))))) ? !(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordNumberImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(((java.util.function.Function<Object, Object>) (Data_Number.abs)).apply(v1_1)))).apply(v_0) instanceof Data_Ordering.GT)))) : !(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordNumberImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(((java.util.function.Function<Object, Object>) (Data_Number.abs)).apply((((Double) (v1_1)) - ((Double) (v2_2))))))).apply((((Double) ((((Double) (v_0)) * ((Double) (((java.util.function.Function<Object, Object>) (Data_Number.abs)).apply((((Double) (v1_1)) + ((Double) (v2_2))))))))) / ((Double) (2.0)))) instanceof Data_Ordering.GT))))));
public static final Object eqApproximate = ((java.util.function.Function<Object, Object>) (Data_Number_Approximate.eqRelative)).apply(0.000001);
public static final Object neqApproximate = (java.util.function.Function<Object, Object>) (x_0) -> (java.util.function.Function<Object, Object>) (y_1) -> !(((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Number_Approximate.eqRelative)).apply(0.000001))).apply(x_0))).apply(y_1))));
public static final Object eqAbsolute = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (x_1) -> (java.util.function.Function<Object, Object>) (y_2) -> !(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordNumberImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(((java.util.function.Function<Object, Object>) (Data_Number.abs)).apply((((Double) (x_1)) - ((Double) (y_2))))))).apply(v_0) instanceof Data_Ordering.GT))));
}
