public class Data_Show_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object intercalate = FFI_STUB;
    public static Object intercalate(Object... args) { return null; }

public static final Object genericShowArgsNoArguments = new java.util.LinkedHashMap<String, Object>() {{ put("genericShowArgs", (java.util.function.Function<Object, Object>) (v_0) -> new Object[]{}); }};
public static final Object genericShowArgsArgument = (java.util.function.Function<Object, Object>) (dictShow_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericShowArgs", (java.util.function.Function<Object, Object>) (v_1) -> new Object[]{((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply(v_1)}); }};
public static final Object genericShowArgs = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("genericShowArgs");
public static final Object genericShowArgsProduct = (java.util.function.Function<Object, Object>) (dictGenericShowArgs_0) -> (java.util.function.Function<Object, Object>) (dictGenericShowArgs1_1) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericShowArgs", (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup.concatArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericShowArgs_0).get("genericShowArgs"))).apply((((Data_Generic_Rep.Product) v_2).value0))))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericShowArgs1_1).get("genericShowArgs"))).apply((((Data_Generic_Rep.Product) v_2).value1)))); }};
public static final Object genericShowConstructor = (java.util.function.Function<Object, Object>) (dictGenericShowArgs_0) -> (java.util.function.Function<Object, Object>) (dictIsSymbol_1) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericShow'", (java.util.function.Function<Object, Object>) (v_2) -> ((new java.util.function.Supplier<Object>() { Object ctor_3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_1).get("reflectSymbol"))).apply(new Type_Proxy.Proxy()); public Object get() { return ((new java.util.function.Supplier<Object>() { Object v1_4 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericShowArgs_0).get("genericShowArgs"))).apply(v_2); public Object get() { return ( ((Boolean) ((((Integer) (((Object[]) v1_4).length)) == ((Integer) (0))))) ? ctor_3 : (((String) ((((String) ("(")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Show_Generic.intercalate)).apply(" "))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Semigroup.concatArray)).apply(new Object[]{ctor_3}))).apply(v1_4))))))) + ((String) (")")))); } })).get(); } })).get()); }};
public static final Object genericShowprime = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("genericShow'");
public static final Object genericShowNoConstructors = new java.util.LinkedHashMap<String, Object>() {{ put("genericShow'", (java.util.function.Function<Object, Object>) (a_0) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_Show_Generic.genericShowNoConstructors).get("genericShow'"))).apply(a_0)); }};
public static final Object genericShowSum = (java.util.function.Function<Object, Object>) (dictGenericShow_0) -> (java.util.function.Function<Object, Object>) (dictGenericShow1_1) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericShow'", (java.util.function.Function<Object, Object>) (v_2) -> ( ((Boolean) ((v_2 instanceof Data_Generic_Rep.Inl))) ? ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericShow_0).get("genericShow'"))).apply((((Data_Generic_Rep.Inl) v_2).value0)) : ( ((Boolean) ((v_2 instanceof Data_Generic_Rep.Inr))) ? ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericShow1_1).get("genericShow'"))).apply((((Data_Generic_Rep.Inr) v_2).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }};
public static final Object genericShow = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> (java.util.function.Function<Object, Object>) (dictGenericShow_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericShow_1).get("genericShow'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0).get("from"))).apply(x_2));
}
