public class Data_Monoid_Disj {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Disj = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showDisj = (java.util.function.Function<Object, Object>) (dictShow_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1) -> (((String) ((((String) ("(Disj ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")")))); }};
public static final Object semiringDisj = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("zero", ((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0).get("ff")); put("one", ((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0).get("tt")); put("add", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0).get("disj"))).apply(v_1))).apply(v1_2)); put("mul", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0).get("conj"))).apply(v_1))).apply(v1_2)); }};
public static final Object semigroupDisj = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0).get("disj"))).apply(v_1))).apply(v1_2)); }};
public static final Object ordDisj = (java.util.function.Function<Object, Object>) (dictOrd_0) -> dictOrd_0;
public static final Object monoidDisj = (java.util.function.Function<Object, Object>) (dictHeytingAlgebra_0) -> ((new java.util.function.Supplier<Object>() { Object semigroupDisj1_1 = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0).get("disj"))).apply(v_1))).apply(v1_2)); }}; public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", ((java.util.LinkedHashMap<String, Object>) dictHeytingAlgebra_0).get("ff")); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> semigroupDisj1_1); }}; } })).get();
public static final Object functorDisj = new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (m_1) -> ((java.util.function.Function<Object, Object>) (f_0)).apply(m_1)); }};
public static final Object eqDisj = (java.util.function.Function<Object, Object>) (dictEq_0) -> dictEq_0;
public static final Object eq1Disj = new java.util.LinkedHashMap<String, Object>() {{ put("eq1", (java.util.function.Function<Object, Object>) (dictEq_0) -> ((java.util.LinkedHashMap<String, Object>) dictEq_0).get("eq")); }};
public static final Object ord1Disj = new java.util.LinkedHashMap<String, Object>() {{ put("compare1", (java.util.function.Function<Object, Object>) (dictOrd_0) -> ((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare")); put("Eq10", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Disj.eq1Disj); }};
public static final Object boundedDisj = (java.util.function.Function<Object, Object>) (dictBounded_0) -> dictBounded_0;
public static final Object applyDisj = new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ((java.util.function.Function<Object, Object>) (v_0)).apply(v1_1)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Disj.functorDisj); }};
public static final Object bindDisj = new java.util.LinkedHashMap<String, Object>() {{ put("bind", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (f_1) -> ((java.util.function.Function<Object, Object>) (f_1)).apply(v_0)); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Disj.applyDisj); }};
public static final Object applicativeDisj = new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (x_0) -> x_0); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Disj.applyDisj); }};
public static final Object monadDisj = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Disj.applicativeDisj); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Disj.bindDisj); }};
}
