public class Data_Profunctor_Choice {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object right = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("right");
public static final Object left = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("left");
public static final Object splitChoice = (java.util.function.Function<Object, Object>) (dictSemigroupoid_0) -> (java.util.function.Function<Object, Object>) (dictChoice_1) -> (java.util.function.Function<Object, Object>) (l_2) -> (java.util.function.Function<Object, Object>) (r_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroupoid_0).get("compose"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictChoice_1).get("right"))).apply(r_3)))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictChoice_1).get("left"))).apply(l_2));
public static final Object fanin = (java.util.function.Function<Object, Object>) (dictSemigroupoid_0) -> (java.util.function.Function<Object, Object>) (dictChoice_1) -> ((new java.util.function.Supplier<Object>() { Object Profunctor0_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictChoice_1).get("Profunctor0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (l_3) -> (java.util.function.Function<Object, Object>) (r_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Profunctor0_2).get("dimap"))).apply((java.util.function.Function<Object, Object>) (x_5) -> x_5))).apply((java.util.function.Function<Object, Object>) (v2_5) -> ( ((Boolean) ((v2_5 instanceof Data_Either.Left))) ? (((Data_Either.Left) v2_5).value0) : ( ((Boolean) ((v2_5 instanceof Data_Either.Right))) ? (((Data_Either.Right) v2_5).value0) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroupoid_0).get("compose"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictChoice_1).get("right"))).apply(r_4)))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictChoice_1).get("left"))).apply(l_3))); } })).get();
public static final Object choiceFn = new java.util.LinkedHashMap<String, Object>() {{ put("left", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ( ((Boolean) ((v1_1 instanceof Data_Either.Left))) ? new Data_Either.Left(((java.util.function.Function<Object, Object>) (v_0)).apply((((Data_Either.Left) v1_1).value0))) : ( ((Boolean) ((v1_1 instanceof Data_Either.Right))) ? new Data_Either.Right((((Data_Either.Right) v1_1).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); put("right", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (m_1) -> ( ((Boolean) ((m_1 instanceof Data_Either.Left))) ? new Data_Either.Left((((Data_Either.Left) m_1).value0)) : ( ((Boolean) ((m_1 instanceof Data_Either.Right))) ? new Data_Either.Right(((java.util.function.Function<Object, Object>) (f_0)).apply((((Data_Either.Right) m_1).value0))) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); put("Profunctor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Profunctor.profunctorFn); }};
}
