public class Data_Semigroup {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object concatArray = FFI_STUB;
    public static Object concatArray(Object... args) { return null; }
    public static Object concatString = FFI_STUB;
    public static Object concatString(Object... args) { return null; }

public static final Object semigroupVoid = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_0) -> Data_Void.absurd); }};
public static final Object semigroupUnit = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> Data_Unit.unit); }};
public static final Object semigroupString = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (a) -> (java.util.function.Function<Object, Object>) (b) -> a.toString() + b.toString()); }};
public static final Object semigroupRecordNil = new java.util.LinkedHashMap<String, Object>() {{ put("appendRecord", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (java.util.function.Function<Object, Object>) (v2_2) -> new java.util.LinkedHashMap<String, Object>() {{ }}); }};
public static final Object semigroupProxy = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> new Type_Proxy.Proxy()); }};
public static final Object semigroupArray = new java.util.LinkedHashMap<String, Object>() {{ put("append", Data_Semigroup.concatArray); }};
public static final Object appendRecord = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("appendRecord");
public static final Object semigroupRecord = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (dictSemigroupRecord_1) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroupRecord_1).get("appendRecord"))).apply(new Type_Proxy.Proxy())); }};
public static final Object append = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("append");
public static final Object semigroupFn = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (g_2) -> (java.util.function.Function<Object, Object>) (x_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append"))).apply(((java.util.function.Function<Object, Object>) (f_1)).apply(x_3)))).apply(((java.util.function.Function<Object, Object>) (g_2)).apply(x_3))); }};
public static final Object semigroupRecordCons = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (dictSemigroupRecord_2) -> (java.util.function.Function<Object, Object>) (dictSemigroup_3) -> new java.util.LinkedHashMap<String, Object>() {{ put("appendRecord", (java.util.function.Function<Object, Object>) (v_4) -> (java.util.function.Function<Object, Object>) (ra_5) -> (java.util.function.Function<Object, Object>) (rb_6) -> ((new java.util.function.Supplier<Object>() { Object key_7 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_0).get("reflectSymbol"))).apply(new Type_Proxy.Proxy()); public Object get() { return ((new java.util.function.Supplier<Object>() { Object get_8 = ((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(key_7); public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeSet)).apply(key_7))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_3).get("append"))).apply(((java.util.function.Function<Object, Object>) (get_8)).apply(ra_5)))).apply(((java.util.function.Function<Object, Object>) (get_8)).apply(rb_6))))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroupRecord_2).get("appendRecord"))).apply(new Type_Proxy.Proxy()))).apply(ra_5))).apply(rb_6)); } })).get(); } })).get()); }};
}
