public class Data_Profunctor_Strong {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object strongFn = new java.util.LinkedHashMap<String, Object>() {{ put("first", (java.util.function.Function<Object, Object>) (a2b_0) -> (java.util.function.Function<Object, Object>) (v_1) -> new Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (a2b_0)).apply((((Data_Tuple.Tuple) v_1).value0)), (((Data_Tuple.Tuple) v_1).value1))); put("second", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (m_1) -> new Data_Tuple.Tuple((((Data_Tuple.Tuple) m_1).value0), ((java.util.function.Function<Object, Object>) (f_0)).apply((((Data_Tuple.Tuple) m_1).value1)))); put("Profunctor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Profunctor.profunctorFn); }};
public static final Object second = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("second");
public static final Object first = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("first");
public static final Object splitStrong = (java.util.function.Function<Object, Object>) (dictSemigroupoid_0) -> (java.util.function.Function<Object, Object>) (dictStrong_1) -> (java.util.function.Function<Object, Object>) (l_2) -> (java.util.function.Function<Object, Object>) (r_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroupoid_0).get("compose"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictStrong_1).get("second"))).apply(r_3)))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictStrong_1).get("first"))).apply(l_2));
public static final Object fanout = (java.util.function.Function<Object, Object>) (dictSemigroupoid_0) -> (java.util.function.Function<Object, Object>) (dictStrong_1) -> ((new java.util.function.Supplier<Object>() { Object Profunctor0_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictStrong_1).get("Profunctor0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (l_3) -> (java.util.function.Function<Object, Object>) (r_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Profunctor0_2).get("dimap"))).apply((java.util.function.Function<Object, Object>) (a_5) -> new Data_Tuple.Tuple(a_5, a_5)))).apply((java.util.function.Function<Object, Object>) (x_5) -> x_5))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroupoid_0).get("compose"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictStrong_1).get("second"))).apply(r_4)))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictStrong_1).get("first"))).apply(l_3))); } })).get();
}
