public class Data_Bifunctor {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object bimap = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("bimap");
public static final Object bivoid = (java.util.function.Function<Object, Object>) (dictBifunctor_0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBifunctor_0).get("bimap"))).apply((java.util.function.Function<Object, Object>) (v_1) -> Data_Unit.unit))).apply((java.util.function.Function<Object, Object>) (v_1) -> Data_Unit.unit);
public static final Object lmap = (java.util.function.Function<Object, Object>) (dictBifunctor_0) -> (java.util.function.Function<Object, Object>) (f_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBifunctor_0).get("bimap"))).apply(f_1))).apply((java.util.function.Function<Object, Object>) (x_2) -> x_2);
public static final Object rmap = (java.util.function.Function<Object, Object>) (dictBifunctor_0) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBifunctor_0).get("bimap"))).apply((java.util.function.Function<Object, Object>) (x_1) -> x_1);
public static final Object bifunctorTuple = new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (g_1) -> (java.util.function.Function<Object, Object>) (v_2) -> new Data_Tuple.Tuple(((java.util.function.Function<Object, Object>) (f_0)).apply((((Data_Tuple.Tuple) v_2).value0)), ((java.util.function.Function<Object, Object>) (g_1)).apply((((Data_Tuple.Tuple) v_2).value1)))); }};
public static final Object bifunctorEither = new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (java.util.function.Function<Object, Object>) (v2_2) -> ( ((Boolean) ((v2_2 instanceof Data_Either.Left))) ? new Data_Either.Left(((java.util.function.Function<Object, Object>) (v_0)).apply((((Data_Either.Left) v2_2).value0))) : ( ((Boolean) ((v2_2 instanceof Data_Either.Right))) ? new Data_Either.Right(((java.util.function.Function<Object, Object>) (v1_1)).apply((((Data_Either.Right) v2_2).value0))) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }};
public static final Object bifunctorConst = new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (f_0)).apply(v1_2)); }};
}
