public class Data_Maybe {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final class Nothing {
            
            public Nothing() {
                
            }
        }
public static final class Just {
            public final Object value0;
            public Just(Object value0) {
                this.value0 = value0;
            }
        }
public static final Object Nothing = new Data_Maybe.Nothing();
public static final Object Just = (java.util.function.Function<Object, Object>) (value0) -> new Data_Maybe.Just(value0);
public static final Object showMaybe = (java.util.function.Function<Object, Object>) (dictShow_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1) -> ( ((Boolean) ((v_1 instanceof Data_Maybe.Just))) ? (((String) ((((String) ("(Just ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply((((Data_Maybe.Just) v_1).value0))))))) + ((String) (")"))) : ( ((Boolean) ((v_1 instanceof Data_Maybe.Nothing))) ? "Nothing" : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }};
public static final Object semigroupMaybe = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ( ((Boolean) ((v_1 instanceof Data_Maybe.Nothing))) ? v1_2 : ( ((Boolean) ((v1_2 instanceof Data_Maybe.Nothing))) ? v_1 : ( ((Boolean) ((((Boolean) ((v_1 instanceof Data_Maybe.Just))) && ((Boolean) ((v1_2 instanceof Data_Maybe.Just)))))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append"))).apply((((Data_Maybe.Just) v_1).value0)))).apply((((Data_Maybe.Just) v1_2).value0))) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); }};
public static final Object optional = (java.util.function.Function<Object, Object>) (dictAlt_0) -> ((new java.util.function.Supplier<Object>() { Object Functor0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictAlt_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (dictApplicative_2) -> (java.util.function.Function<Object, Object>) (a_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictAlt_0).get("alt"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Functor0_1).get("map"))).apply(Data_Maybe.Just))).apply(a_3)))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_2).get("pure"))).apply(new Data_Maybe.Nothing())); } })).get();
public static final Object monoidMaybe = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> ((new java.util.function.Supplier<Object>() { Object semigroupMaybe1_1 = new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ( ((Boolean) ((v_1 instanceof Data_Maybe.Nothing))) ? v1_2 : ( ((Boolean) ((v1_2 instanceof Data_Maybe.Nothing))) ? v_1 : ( ((Boolean) ((((Boolean) ((v_1 instanceof Data_Maybe.Just))) && ((Boolean) ((v1_2 instanceof Data_Maybe.Just)))))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append"))).apply((((Data_Maybe.Just) v_1).value0)))).apply((((Data_Maybe.Just) v1_2).value0))) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); }}; public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", new Data_Maybe.Nothing()); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> semigroupMaybe1_1); }}; } })).get();
public static final Object maybeprime = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (java.util.function.Function<Object, Object>) (v2_2) -> ( ((Boolean) ((v2_2 instanceof Data_Maybe.Nothing))) ? ((java.util.function.Function<Object, Object>) (v_0)).apply(Data_Unit.unit) : ( ((Boolean) ((v2_2 instanceof Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (v1_1)).apply((((Data_Maybe.Just) v2_2).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()));
public static final Object maybe = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (java.util.function.Function<Object, Object>) (v2_2) -> ( ((Boolean) ((v2_2 instanceof Data_Maybe.Nothing))) ? v_0 : ( ((Boolean) ((v2_2 instanceof Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (v1_1)).apply((((Data_Maybe.Just) v2_2).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()));
public static final Object isNothing = (java.util.function.Function<Object, Object>) (v2_0) -> ( ((Boolean) ((v2_0 instanceof Data_Maybe.Nothing))) ? true : ( ((Boolean) ((v2_0 instanceof Data_Maybe.Just))) ? false : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()));
public static final Object isJust = (java.util.function.Function<Object, Object>) (v2_0) -> ( ((Boolean) ((v2_0 instanceof Data_Maybe.Nothing))) ? false : ( ((Boolean) ((v2_0 instanceof Data_Maybe.Just))) ? true : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()));
public static final Object genericMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("to", (java.util.function.Function<Object, Object>) (x_0) -> ( ((Boolean) ((x_0 instanceof Data_Generic_Rep.Inl))) ? new Data_Maybe.Nothing() : ( ((Boolean) ((x_0 instanceof Data_Generic_Rep.Inr))) ? new Data_Maybe.Just((((Data_Generic_Rep.Inr) x_0).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); put("from", (java.util.function.Function<Object, Object>) (x_0) -> ( ((Boolean) ((x_0 instanceof Data_Maybe.Nothing))) ? new Data_Generic_Rep.Inl(new Data_Generic_Rep.NoArguments()) : ( ((Boolean) ((x_0 instanceof Data_Maybe.Just))) ? new Data_Generic_Rep.Inr((((Data_Maybe.Just) x_0).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }};
public static final Object functorMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ( ((Boolean) ((v1_1 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (v_0)).apply((((Data_Maybe.Just) v1_1).value0))) : new Data_Maybe.Nothing())); }};
public static final Object invariantMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("imap", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ( ((Boolean) ((v1_2 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (f_0)).apply((((Data_Maybe.Just) v1_2).value0))) : new Data_Maybe.Nothing())); }};
public static final Object fromMaybeprime = (java.util.function.Function<Object, Object>) (a_0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Maybe.maybeprime)).apply(a_0))).apply((java.util.function.Function<Object, Object>) (x_1) -> x_1);
public static final Object fromMaybe = (java.util.function.Function<Object, Object>) (a_0) -> (java.util.function.Function<Object, Object>) (v2_1) -> ( ((Boolean) ((v2_1 instanceof Data_Maybe.Nothing))) ? a_0 : ( ((Boolean) ((v2_1 instanceof Data_Maybe.Just))) ? (((Data_Maybe.Just) v2_1).value0) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()));
public static final Object fromJust = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (v_1) -> ( ((Boolean) ((v_1 instanceof Data_Maybe.Just))) ? (((Data_Maybe.Just) v_1).value0) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get());
public static final Object extendMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("extend", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ( ((Boolean) ((v1_1 instanceof Data_Maybe.Nothing))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (v_0)).apply(v1_1)))); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe.functorMaybe); }};
public static final Object eqMaybe = (java.util.function.Function<Object, Object>) (dictEq_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_1) -> (java.util.function.Function<Object, Object>) (y_2) -> ( ((Boolean) ((x_1 instanceof Data_Maybe.Nothing))) ? (y_2 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_1 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_2 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq_0).get("eq"))).apply((((Data_Maybe.Just) x_1).value0)))).apply((((Data_Maybe.Just) y_2).value0)))))))))); }};
public static final Object ordMaybe = (java.util.function.Function<Object, Object>) (dictOrd_0) -> ((new java.util.function.Supplier<Object>() { Object eqMaybe1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_2) -> (java.util.function.Function<Object, Object>) (y_3) -> ( ((Boolean) ((x_2 instanceof Data_Maybe.Nothing))) ? (y_3 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_2 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_3 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("eq"))).apply((((Data_Maybe.Just) x_2).value0)))).apply((((Data_Maybe.Just) y_3).value0)))))))))); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (x_2) -> (java.util.function.Function<Object, Object>) (y_3) -> ( ((Boolean) ((x_2 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((y_3 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.EQ() : new Data_Ordering.LT()) : ( ((Boolean) ((y_3 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.GT() : ( ((Boolean) ((((Boolean) ((x_2 instanceof Data_Maybe.Just))) && ((Boolean) ((y_3 instanceof Data_Maybe.Just)))))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply((((Data_Maybe.Just) x_2).value0)))).apply((((Data_Maybe.Just) y_3).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> eqMaybe1_1); }}; } })).get();
public static final Object eq1Maybe = new java.util.LinkedHashMap<String, Object>() {{ put("eq1", (java.util.function.Function<Object, Object>) (dictEq_0) -> (java.util.function.Function<Object, Object>) (x_1) -> (java.util.function.Function<Object, Object>) (y_2) -> ( ((Boolean) ((x_1 instanceof Data_Maybe.Nothing))) ? (y_2 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_1 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_2 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq_0).get("eq"))).apply((((Data_Maybe.Just) x_1).value0)))).apply((((Data_Maybe.Just) y_2).value0)))))))))); }};
public static final Object ord1Maybe = new java.util.LinkedHashMap<String, Object>() {{ put("compare1", (java.util.function.Function<Object, Object>) (dictOrd_0) -> (java.util.function.Function<Object, Object>) (x_1) -> (java.util.function.Function<Object, Object>) (y_2) -> ( ((Boolean) ((x_1 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((y_2 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.EQ() : new Data_Ordering.LT()) : ( ((Boolean) ((y_2 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.GT() : ( ((Boolean) ((((Boolean) ((x_1 instanceof Data_Maybe.Just))) && ((Boolean) ((y_2 instanceof Data_Maybe.Just)))))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply((((Data_Maybe.Just) x_1).value0)))).apply((((Data_Maybe.Just) y_2).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); put("Eq10", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe.eq1Maybe); }};
public static final Object boundedMaybe = (java.util.function.Function<Object, Object>) (dictBounded_0) -> ((new java.util.function.Supplier<Object>() { Object ordMaybe1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("Ord0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((new java.util.function.Supplier<Object>() { Object eqMaybe1_2 = ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("Eq0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_3) -> (java.util.function.Function<Object, Object>) (y_4) -> ( ((Boolean) ((x_3 instanceof Data_Maybe.Nothing))) ? (y_4 instanceof Data_Maybe.Nothing) : (((Boolean) ((x_3 instanceof Data_Maybe.Just))) && ((Boolean) ((((Boolean) ((y_4 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("eq"))).apply((((Data_Maybe.Just) x_3).value0)))).apply((((Data_Maybe.Just) y_4).value0)))))))))); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (x_3) -> (java.util.function.Function<Object, Object>) (y_4) -> ( ((Boolean) ((x_3 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((y_4 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.EQ() : new Data_Ordering.LT()) : ( ((Boolean) ((y_4 instanceof Data_Maybe.Nothing))) ? new Data_Ordering.GT() : ( ((Boolean) ((((Boolean) ((x_3 instanceof Data_Maybe.Just))) && ((Boolean) ((y_4 instanceof Data_Maybe.Just)))))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("compare"))).apply((((Data_Maybe.Just) x_3).value0)))).apply((((Data_Maybe.Just) y_4).value0)) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> eqMaybe1_2); }}; } })).get(); } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("top", new Data_Maybe.Just(((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("top"))); put("bottom", new Data_Maybe.Nothing()); put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> ordMaybe1_1); }}; } })).get();
public static final Object applyMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ( ((Boolean) ((v_0 instanceof Data_Maybe.Just))) ? ( ((Boolean) ((v1_1 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) ((((Data_Maybe.Just) v_0).value0))).apply((((Data_Maybe.Just) v1_1).value0))) : new Data_Maybe.Nothing()) : ( ((Boolean) ((v_0 instanceof Data_Maybe.Nothing))) ? new Data_Maybe.Nothing() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe.functorMaybe); }};
public static final Object bindMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("bind", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ( ((Boolean) ((v_0 instanceof Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (v1_1)).apply((((Data_Maybe.Just) v_0).value0)) : ( ((Boolean) ((v_0 instanceof Data_Maybe.Nothing))) ? new Data_Maybe.Nothing() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe.applyMaybe); }};
public static final Object semiringMaybe = (java.util.function.Function<Object, Object>) (dictSemiring_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("zero", new Data_Maybe.Nothing()); put("one", new Data_Maybe.Just(((java.util.LinkedHashMap<String, Object>) dictSemiring_0).get("one"))); put("add", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ( ((Boolean) ((v_1 instanceof Data_Maybe.Nothing))) ? v1_2 : ( ((Boolean) ((v1_2 instanceof Data_Maybe.Nothing))) ? v_1 : ( ((Boolean) ((((Boolean) ((v_1 instanceof Data_Maybe.Just))) && ((Boolean) ((v1_2 instanceof Data_Maybe.Just)))))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemiring_0).get("add"))).apply((((Data_Maybe.Just) v_1).value0)))).apply((((Data_Maybe.Just) v1_2).value0))) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); put("mul", (java.util.function.Function<Object, Object>) (x_1) -> (java.util.function.Function<Object, Object>) (y_2) -> ( ((Boolean) ((x_1 instanceof Data_Maybe.Just))) ? ( ((Boolean) ((y_2 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemiring_0).get("mul"))).apply((((Data_Maybe.Just) x_1).value0)))).apply((((Data_Maybe.Just) y_2).value0))) : new Data_Maybe.Nothing()) : new Data_Maybe.Nothing())); }};
public static final Object applicativeMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("pure", Data_Maybe.Just); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe.applyMaybe); }};
public static final Object monadMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe.applicativeMaybe); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe.bindMaybe); }};
public static final Object altMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("alt", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ( ((Boolean) ((v_0 instanceof Data_Maybe.Nothing))) ? v1_1 : v_0)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe.functorMaybe); }};
public static final Object plusMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("empty", new Data_Maybe.Nothing()); put("Alt0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe.altMaybe); }};
public static final Object alternativeMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe.applicativeMaybe); put("Plus1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Maybe.plusMaybe); }};
}
