public class Data_String_CodePoints {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    // FFI provided by ../javapurs-strings/src/Data/String/CodePoints.java
    public static Object _unsafeCodePointAt0 = (java.util.function.Function<Object, Object>) (fallback) -> (java.util.function.Function<Object, Object>) (str) -> {
        String s = (String) str;
        if (s.isEmpty()) throw new RuntimeException("unsafeCodePointAt0: empty string");
        return s.codePointAt(0);
    };

    public static Object _codePointAt = (java.util.function.Function<Object, Object>) (fallback) -> (java.util.function.Function<Object, Object>) (just) -> (java.util.function.Function<Object, Object>) (nothing) -> (java.util.function.Function<Object, Object>) (unsafeCodePointAt0) -> (java.util.function.Function<Object, Object>) (index) -> (java.util.function.Function<Object, Object>) (str) -> {
        int idx = (Integer) index;
        String s = (String) str;
        int len = s.codePointCount(0, s.length());
        if (idx < 0 || idx >= len) return nothing;
        int offset = s.offsetByCodePoints(0, idx);
        return ((java.util.function.Function<Object, Object>) just).apply(s.codePointAt(offset));
    };

    public static Object _countPrefix = (java.util.function.Function<Object, Object>) (fallback) -> (java.util.function.Function<Object, Object>) (unsafeCodePointAt0) -> (java.util.function.Function<Object, Object>) (pred) -> (java.util.function.Function<Object, Object>) (str) -> {
        String s = (String) str;
        int count = 0;
        int i = 0;
        while (i < s.length()) {
            int cp = s.codePointAt(i);
            Boolean res = (Boolean) ((java.util.function.Function<Object, Object>) pred).apply(cp);
            if (!res) break;
            count++;
            i += Character.charCount(cp);
        }
        return count;
    };

    public static Object _fromCodePointArray = (java.util.function.Function<Object, Object>) (singleton) -> (java.util.function.Function<Object, Object>) (cps) -> {
        Object[] arr = (Object[]) cps;
        StringBuilder sb = new StringBuilder(arr.length);
        for (Object cp : arr) {
            sb.appendCodePoint((Integer) cp);
        }
        return sb.toString();
    };

    public static Object _singleton = (java.util.function.Function<Object, Object>) (fallback) -> (java.util.function.Function<Object, Object>) (cp) -> {
        return new String(Character.toChars((Integer) cp));
    };

    public static Object _take = (java.util.function.Function<Object, Object>) (fallback) -> (java.util.function.Function<Object, Object>) (n) -> (java.util.function.Function<Object, Object>) (str) -> {
        int num = (Integer) n;
        String s = (String) str;
        int len = s.codePointCount(0, s.length());
        num = Math.max(0, Math.min(num, len));
        int offset = s.offsetByCodePoints(0, num);
        return s.substring(0, offset);
    };

    public static Object _toCodePointArray = (java.util.function.Function<Object, Object>) (fallback) -> (java.util.function.Function<Object, Object>) (unsafeCodePointAt0) -> (java.util.function.Function<Object, Object>) (str) -> {
        String s = (String) str;
        int len = s.codePointCount(0, s.length());
        Object[] arr = new Object[len];
        int j = 0;
        for (int i = 0; i < s.length(); i += Character.charCount(s.codePointAt(i))) {
            arr[j++] = s.codePointAt(i);
        }
        return arr;
    };


public static final Object showCodePoint = new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_0) -> (((String) ((((String) ("(CodePoint 0x")) + ((String) (((java.util.function.Function<Object, Object>) (Data_String_Common.toUpper)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Int.toStringAs)).apply(16))).apply(v_0))))))) + ((String) (")")))); }};
public static final Object uncons = (java.util.function.Function<Object, Object>) (s_0) -> ((new java.util.function.Supplier<Object>() { Object v_1 = ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(s_0); public Object get() { return ( ((Boolean) ((((Integer) (v_1)) == ((Integer) (0))))) ? new Data_Maybe.Nothing() : ( ((Boolean) ((((Integer) (v_1)) == ((Integer) (1))))) ? new Data_Maybe.Just(new java.util.LinkedHashMap<String, Object>() {{ put("head", ((java.util.function.Function<Object, Object>) (Data_Enum.toCharCode)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_Unsafe.charAt)).apply(0))).apply(s_0))); put("tail", ""); }}) : ((new java.util.function.Supplier<Object>() { Object cu1_2 = ((java.util.function.Function<Object, Object>) (Data_Enum.toCharCode)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_Unsafe.charAt)).apply(1))).apply(s_0)); public Object get() { return ((new java.util.function.Supplier<Object>() { Object cu0_3 = ((java.util.function.Function<Object, Object>) (Data_Enum.toCharCode)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_Unsafe.charAt)).apply(0))).apply(s_0)); public Object get() { return ( ((Boolean) ((((Boolean) ((((Boolean) ((((Integer) (55296)) <= ((Integer) (cu0_3))))) && ((Boolean) ((((Integer) (cu0_3)) <= ((Integer) (56319)))))))) && ((Boolean) ((((Boolean) ((((Integer) (56320)) <= ((Integer) (cu1_2))))) && ((Boolean) ((((Integer) (cu1_2)) <= ((Integer) (57343))))))))))) ? new Data_Maybe.Just(new java.util.LinkedHashMap<String, Object>() {{ put("head", (((Integer) ((((Integer) ((((Integer) ((((Integer) (cu0_3)) - ((Integer) (55296))))) * ((Integer) (1024))))) + ((Integer) ((((Integer) (cu1_2)) - ((Integer) (56320)))))))) + ((Integer) (65536)))); put("tail", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(2))).apply(s_0)); }}) : new Data_Maybe.Just(new java.util.LinkedHashMap<String, Object>() {{ put("head", cu0_3); put("tail", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(1))).apply(s_0)); }})); } })).get(); } })).get())); } })).get();
public static final Object unconsButWithTuple = (java.util.function.Function<Object, Object>) (s_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.uncons)).apply(s_0); public Object get() { return ( ((Boolean) ((__local_var_1 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(new Data_Tuple.Tuple(((java.util.LinkedHashMap<String, Object>) (((Data_Maybe.Just) __local_var_1).value0)).get("head"), ((java.util.LinkedHashMap<String, Object>) (((Data_Maybe.Just) __local_var_1).value0)).get("tail"))) : new Data_Maybe.Nothing()); } })).get();
public static final Object toCodePointArrayFallback = (java.util.function.Function<Object, Object>) (s_0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Unfoldable.unfoldrArrayImpl)).apply(Data_Maybe.isNothing))).apply((java.util.function.Function<Object, Object>) (v_1) -> ( ((Boolean) ((v_1 instanceof Data_Maybe.Just))) ? (((Data_Maybe.Just) v_1).value0) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))).apply(Data_Tuple.fst))).apply(Data_Tuple.snd))).apply(Data_String_CodePoints.unconsButWithTuple))).apply(s_0);
public static final Object unsafeCodePointAt0Fallback = (java.util.function.Function<Object, Object>) (s_0) -> ((new java.util.function.Supplier<Object>() { Object cu0_1 = ((java.util.function.Function<Object, Object>) (Data_Enum.toCharCode)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_Unsafe.charAt)).apply(0))).apply(s_0)); public Object get() { return ( ((Boolean) ((((Boolean) ((((Boolean) ((((Integer) (55296)) <= ((Integer) (cu0_1))))) && ((Boolean) ((((Integer) (cu0_1)) <= ((Integer) (56319)))))))) && ((Boolean) ((((Integer) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(s_0))) > ((Integer) (1)))))))) ? ((new java.util.function.Supplier<Object>() { Object cu1_2 = ((java.util.function.Function<Object, Object>) (Data_Enum.toCharCode)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_Unsafe.charAt)).apply(1))).apply(s_0)); public Object get() { return ( ((Boolean) ((((Boolean) ((((Integer) (56320)) <= ((Integer) (cu1_2))))) && ((Boolean) ((((Integer) (cu1_2)) <= ((Integer) (57343)))))))) ? (((Integer) ((((Integer) ((((Integer) ((((Integer) (cu0_1)) - ((Integer) (55296))))) * ((Integer) (1024))))) + ((Integer) ((((Integer) (cu1_2)) - ((Integer) (56320)))))))) + ((Integer) (65536))) : cu0_1); } })).get() : cu0_1); } })).get();
public static final Object unsafeCodePointAt0 = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints._unsafeCodePointAt0)).apply(Data_String_CodePoints.unsafeCodePointAt0Fallback);
public static final Object toCodePointArray = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints._toCodePointArray)).apply(Data_String_CodePoints.toCodePointArrayFallback))).apply(Data_String_CodePoints.unsafeCodePointAt0);
public static final Object length = (java.util.function.Function<Object, Object>) (x_0) -> ((Object[]) ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(x_0)).length;
public static final Object lastIndexOf = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (s_1) -> ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.lastIndexOf)).apply(p_0))).apply(s_1); public Object get() { return ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((Object[]) ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.take)).apply((((Data_Maybe.Just) __local_var_2).value0)))).apply(s_1))).length) : new Data_Maybe.Nothing()); } })).get();
public static final Object indexOf = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (s_1) -> ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.indexOf)).apply(p_0))).apply(s_1); public Object get() { return ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((Object[]) ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.take)).apply((((Data_Maybe.Just) __local_var_2).value0)))).apply(s_1))).length) : new Data_Maybe.Nothing()); } })).get();
public static final Object fromCharCode = (java.util.function.Function<Object, Object>) (x_0) -> ((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.singleton)).apply(((new java.util.function.Supplier<Object>() { Object v_1 = ((java.util.function.Function<Object, Object>) (Data_Enum.charToEnum)).apply(x_0); public Object get() { return ( ((Boolean) ((v_1 instanceof Data_Maybe.Just))) ? (((Data_Maybe.Just) v_1).value0) : ( ((Boolean) ((v_1 instanceof Data_Maybe.Nothing))) ? ( ((Boolean) ((((Integer) (x_0)) < ((Integer) (((java.util.function.Function<Object, Object>) (Data_Enum.toCharCode)).apply(Data_Bounded.bottomChar)))))) ? Data_Bounded.bottomChar : Data_Bounded.topChar) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); } })).get());
public static final Object singletonFallback = (java.util.function.Function<Object, Object>) (v_0) -> ( ((Boolean) ((((Integer) (v_0)) <= ((Integer) (65535))))) ? ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.fromCharCode)).apply(v_0) : (((String) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.fromCharCode)).apply((((Integer) ((((Integer) ((((Integer) (v_0)) - ((Integer) (65536))))) / ((Integer) (1024))))) + ((Integer) (55296)))))) + ((String) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.fromCharCode)).apply((((Integer) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_EuclideanRing.intMod)).apply((((Integer) (v_0)) - ((Integer) (65536)))))).apply(1024))) + ((Integer) (56320))))))));
public static final Object fromCodePointArray = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints._fromCodePointArray)).apply(Data_String_CodePoints.singletonFallback);
public static final Object singleton = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints._singleton)).apply(Data_String_CodePoints.singletonFallback);
public static final Object takeFallback = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ((java.util.function.Supplier<Object>) () -> { Object __tco_v_0 = v_0; Object __tco_v1_1 = v1_1; while(true) { final Object __final_v_0 = __tco_v_0; final Object __final_v1_1 = __tco_v1_1; try { return ( ((Boolean) ((((Integer) (__final_v_0)) < ((Integer) (1))))) ? "" : ((new java.util.function.Supplier<Object>() { Object v2_2 = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.uncons)).apply(__final_v1_1); public Object get() { return ( ((Boolean) ((v2_2 instanceof Data_Maybe.Just))) ? (((String) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.singleton)).apply(((java.util.LinkedHashMap<String, Object>) (((Data_Maybe.Just) v2_2).value0)).get("head")))) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.takeFallback)).apply((((Integer) (__final_v_0)) - ((Integer) (1)))))).apply(((java.util.LinkedHashMap<String, Object>) (((Data_Maybe.Just) v2_2).value0)).get("tail"))))) : __final_v1_1); } })).get()); } catch (TcoLoop __tco_ex) { __tco_v_0 = __tco_ex.args[0]; __tco_v1_1 = __tco_ex.args[1]; } } }).get();
public static final Object take = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints._take)).apply(Data_String_CodePoints.takeFallback);
public static final Object lastIndexOfprime = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (i_1) -> (java.util.function.Function<Object, Object>) (s_2) -> ((new java.util.function.Supplier<Object>() { Object __local_var_3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.lastIndexOfprime)).apply(p_0))).apply(((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(i_1))).apply(s_2))))).apply(s_2); public Object get() { return ( ((Boolean) ((__local_var_3 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(((Object[]) ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.take)).apply((((Data_Maybe.Just) __local_var_3).value0)))).apply(s_2))).length) : new Data_Maybe.Nothing()); } })).get();
public static final Object splitAt = (java.util.function.Function<Object, Object>) (i_0) -> (java.util.function.Function<Object, Object>) (s_1) -> ((new java.util.function.Supplier<Object>() { Object before_2 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(i_0))).apply(s_1); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("before", before_2); put("after", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(before_2)))).apply(s_1)); }}; } })).get();
public static final Object eqCodePoint = new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_0) -> (java.util.function.Function<Object, Object>) (y_1) -> (((Integer) (x_0)) == ((Integer) (y_1)))); }};
public static final Object ordCodePoint = new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (x_0) -> (java.util.function.Function<Object, Object>) (y_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(x_0))).apply(y_1)); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_String_CodePoints.eqCodePoint); }};
public static final Object drop = (java.util.function.Function<Object, Object>) (n_0) -> (java.util.function.Function<Object, Object>) (s_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(n_0))).apply(s_1))))).apply(s_1);
public static final Object indexOfprime = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (i_1) -> (java.util.function.Function<Object, Object>) (s_2) -> ((new java.util.function.Supplier<Object>() { Object s_prime__3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(i_1))).apply(s_2))))).apply(s_2); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.indexOf)).apply(p_0))).apply(s_prime__3); public Object get() { return ( ((Boolean) ((__local_var_4 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just((((Integer) (i_1)) + ((Integer) (((Object[]) ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.take)).apply((((Data_Maybe.Just) __local_var_4).value0)))).apply(s_prime__3))).length)))) : new Data_Maybe.Nothing()); } })).get(); } })).get();
public static final Object countTail = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (s_1) -> (java.util.function.Function<Object, Object>) (accum_2) -> ((java.util.function.Supplier<Object>) () -> { Object __tco_p_0 = p_0; Object __tco_s_1 = s_1; Object __tco_accum_2 = accum_2; while(true) { final Object __final_p_0 = __tco_p_0; final Object __final_s_1 = __tco_s_1; final Object __final_accum_2 = __tco_accum_2; try { return ((new java.util.function.Supplier<Object>() { Object v_3 = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.uncons)).apply(__final_s_1); public Object get() { return ( ((Boolean) ((((Boolean) ((v_3 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (__final_p_0)).apply(((java.util.LinkedHashMap<String, Object>) (((Data_Maybe.Just) v_3).value0)).get("head"))))))) ? ((java.util.function.Supplier<Object>) () -> { throw new TcoLoop("countTail", new Object[]{__final_p_0, ((java.util.LinkedHashMap<String, Object>) (((Data_Maybe.Just) v_3).value0)).get("tail"), (((Integer) (__final_accum_2)) + ((Integer) (1)))}); }).get() : __final_accum_2); } })).get(); } catch (TcoLoop __tco_ex) { __tco_p_0 = __tco_ex.args[0]; __tco_s_1 = __tco_ex.args[1]; __tco_accum_2 = __tco_ex.args[2]; } } }).get();
public static final Object countFallback = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (s_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.countTail)).apply(p_0))).apply(s_1))).apply(0);
public static final Object countPrefix = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints._countPrefix)).apply(Data_String_CodePoints.countFallback))).apply(Data_String_CodePoints.unsafeCodePointAt0);
public static final Object dropWhile = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (s_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.drop)).apply(((java.util.function.Function<Object, Object>) (Data_String_CodeUnits.length)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.countPrefix)).apply(p_0))).apply(s_1)))).apply(s_1))))).apply(s_1);
public static final Object takeWhile = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (s_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.take)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints.countPrefix)).apply(p_0))).apply(s_1)))).apply(s_1);
public static final Object codePointFromChar = (java.util.function.Function<Object, Object>) (x_0) -> ((java.util.function.Function<Object, Object>) (Data_Enum.toCharCode)).apply(x_0);
public static final Object codePointAtFallback = (java.util.function.Function<Object, Object>) (n_0) -> (java.util.function.Function<Object, Object>) (s_1) -> ((java.util.function.Supplier<Object>) () -> { Object __tco_n_0 = n_0; Object __tco_s_1 = s_1; while(true) { final Object __final_n_0 = __tco_n_0; final Object __final_s_1 = __tco_s_1; try { return ((new java.util.function.Supplier<Object>() { Object v_2 = ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.uncons)).apply(__final_s_1); public Object get() { return ( ((Boolean) ((v_2 instanceof Data_Maybe.Just))) ? ( ((Boolean) ((((Integer) (__final_n_0)) == ((Integer) (0))))) ? new Data_Maybe.Just(((java.util.LinkedHashMap<String, Object>) (((Data_Maybe.Just) v_2).value0)).get("head")) : ((java.util.function.Supplier<Object>) () -> { throw new TcoLoop("codePointAtFallback", new Object[]{(((Integer) (__final_n_0)) - ((Integer) (1))), ((java.util.LinkedHashMap<String, Object>) (((Data_Maybe.Just) v_2).value0)).get("tail")}); }).get()) : new Data_Maybe.Nothing()); } })).get(); } catch (TcoLoop __tco_ex) { __tco_n_0 = __tco_ex.args[0]; __tco_s_1 = __tco_ex.args[1]; } } }).get();
public static final Object codePointAt = (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ( ((Boolean) ((((Integer) (v_0)) < ((Integer) (0))))) ? new Data_Maybe.Nothing() : ( ((Boolean) ((((Integer) (v_0)) == ((Integer) (0))))) ? ( ((Boolean) (java.util.Objects.equals(v1_1, ""))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(((java.util.function.Function<Object, Object>) (Data_String_CodePoints.unsafeCodePointAt0)).apply(v1_1))) : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_String_CodePoints._codePointAt)).apply(Data_String_CodePoints.codePointAtFallback))).apply(Data_Maybe.Just))).apply(new Data_Maybe.Nothing()))).apply(Data_String_CodePoints.unsafeCodePointAt0))).apply(v_0))).apply(v1_1)));
public static final Object boundedCodePoint = new java.util.LinkedHashMap<String, Object>() {{ put("bottom", 0); put("top", 1114111); put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_String_CodePoints.ordCodePoint); }};
public static final Object boundedEnumCodePoint = new java.util.LinkedHashMap<String, Object>() {{ put("cardinality", 1114112); put("fromEnum", (java.util.function.Function<Object, Object>) (v_0) -> v_0); put("toEnum", (java.util.function.Function<Object, Object>) (n_0) -> ( ((Boolean) ((((Boolean) ((((Integer) (n_0)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (n_0)) <= ((Integer) (1114111)))))))) ? new Data_Maybe.Just(n_0) : new Data_Maybe.Nothing())); put("Bounded0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_String_CodePoints.boundedCodePoint); put("Enum1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_String_CodePoints.enumCodePoint); }};
public static final Object enumCodePoint = new java.util.LinkedHashMap<String, Object>() {{ put("succ", (java.util.function.Function<Object, Object>) (a_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = (((Integer) (a_0)) + ((Integer) (1))); public Object get() { return ( ((Boolean) ((((Boolean) ((((Integer) (__local_var_1)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (__local_var_1)) <= ((Integer) (1114111)))))))) ? new Data_Maybe.Just(__local_var_1) : new Data_Maybe.Nothing()); } })).get()); put("pred", (java.util.function.Function<Object, Object>) (a_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = (((Integer) (a_0)) - ((Integer) (1))); public Object get() { return ( ((Boolean) ((((Boolean) ((((Integer) (__local_var_1)) >= ((Integer) (0))))) && ((Boolean) ((((Integer) (__local_var_1)) <= ((Integer) (1114111)))))))) ? new Data_Maybe.Just(__local_var_1) : new Data_Maybe.Nothing()); } })).get()); put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_String_CodePoints.ordCodePoint); }};
}
