public class Data_String_Unicode {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object convertFull = (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (x_1) -> ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.fromCodePointArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Bind.arrayBind)).apply(((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(x_1)))).apply(f_0));
public static final Object toLower = ((java.util.function.Function<Object, Object>) (Data_String_Unicode.convertFull)).apply(Data_CodePoint_Unicode_Internal_Casing.lower);
public static final Object toUpper = ((java.util.function.Function<Object, Object>) (Data_String_Unicode.convertFull)).apply(Data_CodePoint_Unicode_Internal_Casing.upper);
public static final Object convert = (java.util.function.Function<Object, Object>) (f_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Data_Functor.arrayMap)).apply(f_0); public Object get() { return (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.fromCodePointArray)).apply(((java.util.function.Function<Object, Object>) (__local_var_1)).apply(x_2)); } })).get(); public Object get() { return (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (__local_var_1)).apply(((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(x_2)); } })).get();
public static final Object toLowerSimple = ((java.util.function.Function<Object, Object>) (Data_String_Unicode.convert)).apply(Data_CodePoint_Unicode_Internal.uTowlower);
public static final Object toUpperSimple = ((java.util.function.Function<Object, Object>) (Data_String_Unicode.convert)).apply(Data_CodePoint_Unicode_Internal.uTowupper);
public static final Object caseFoldSimple = ((java.util.function.Function<Object, Object>) (Data_String_Unicode.convert)).apply(Data_CodePoint_Unicode_Internal_Casing.fold);
public static final Object caseFold = ((java.util.function.Function<Object, Object>) (Data_String_Unicode.convertFull)).apply(Data_CodePoint_Unicode_Internal_Casing.foldFull);
public static final Object caselessMatch = (java.util.function.Function<Object, Object>) (s1_0) -> (java.util.function.Function<Object, Object>) (s2_1) -> java.util.Objects.equals(((java.util.function.Function<Object, Object>) (Data_String_CodePoints.fromCodePointArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Bind.arrayBind)).apply(((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(s1_0)))).apply(Data_CodePoint_Unicode_Internal_Casing.foldFull)), ((java.util.function.Function<Object, Object>) (Data_String_CodePoints.fromCodePointArray)).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Bind.arrayBind)).apply(((java.util.function.Function<Object, Object>) (Data_String_CodePoints.toCodePointArray)).apply(s2_1)))).apply(Data_CodePoint_Unicode_Internal_Casing.foldFull)));
}
