public class Data_Functor_Clown {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Clown = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showClown = (java.util.function.Function<Object, Object>) (dictShow_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1) -> (((String) ((((String) ("(Clown ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")")))); }};
public static final Object profunctorClown = (java.util.function.Function<Object, Object>) (dictContravariant_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("dimap", (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictContravariant_0).get("cmap"))).apply(f_1))).apply(v1_3)); }};
public static final Object ordClown = (java.util.function.Function<Object, Object>) (dictOrd_0) -> dictOrd_0;
public static final Object newtypeClown = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object hoistClown = (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> ((java.util.function.Function<Object, Object>) (f_0)).apply(v_1);
public static final Object functorClown = new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> v1_1); }};
public static final Object eqClown = (java.util.function.Function<Object, Object>) (dictEq_0) -> dictEq_0;
public static final Object bifunctorClown = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictFunctor_0).get("map"))).apply(f_1))).apply(v1_3)); }};
public static final Object biapplyClown = (java.util.function.Function<Object, Object>) (dictApply_0) -> ((new java.util.function.Supplier<Object>() { Object bifunctorClown1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (v1_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("map"))).apply(f_2))).apply(v1_4)); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("biapply", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(v_2))).apply(v1_3)); put("Bifunctor0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> bifunctorClown1_1); }}; } })).get();
public static final Object biapplicativeClown = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> ((new java.util.function.Supplier<Object>() { Object biapplyClown1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0).get("Apply0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((new java.util.function.Supplier<Object>() { Object bifunctorClown1_2 = ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("Functor0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_3) -> (java.util.function.Function<Object, Object>) (v_4) -> (java.util.function.Function<Object, Object>) (v1_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("map"))).apply(f_3))).apply(v1_5)); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("biapply", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (v1_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("apply"))).apply(v_3))).apply(v1_4)); put("Bifunctor0", (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> bifunctorClown1_2); }}; } })).get(); } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("bipure", (java.util.function.Function<Object, Object>) (a_2) -> (java.util.function.Function<Object, Object>) (v_3) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0).get("pure"))).apply(a_2)); put("Biapply0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> biapplyClown1_1); }}; } })).get();
}
