public class Data_Functor_App {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object App = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showApp = (java.util.function.Function<Object, Object>) (dictShow_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1) -> (((String) ((((String) ("(App ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")")))); }};
public static final Object semigroupApp = (java.util.function.Function<Object, Object>) (dictApply_0) -> (java.util.function.Function<Object, Object>) (dictSemigroup_1) -> ((new java.util.function.Supplier<Object>() { Object append_2 = ((java.util.LinkedHashMap<String, Object>) dictSemigroup_1).get("append"); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (v1_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(append_2))).apply(v_3)))).apply(v1_4)); }}; } })).get();
public static final Object plusApp = (java.util.function.Function<Object, Object>) (dictPlus_0) -> dictPlus_0;
public static final Object newtypeApp = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object monoidApp = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0).get("Apply0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (dictMonoid_2) -> ((new java.util.function.Supplier<Object>() { Object semigroupApp2_3 = ((new java.util.function.Supplier<Object>() { Object append_3 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_2).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */)).get("append"); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_4) -> (java.util.function.Function<Object, Object>) (v1_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("apply"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"))).apply(append_3))).apply(v_4)))).apply(v1_5)); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApplicative_0).get("pure"))).apply(((java.util.LinkedHashMap<String, Object>) dictMonoid_2).get("mempty"))); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_4) -> semigroupApp2_3); }}; } })).get(); } })).get();
public static final Object monadPlusApp = (java.util.function.Function<Object, Object>) (dictMonadPlus_0) -> dictMonadPlus_0;
public static final Object monadApp = (java.util.function.Function<Object, Object>) (dictMonad_0) -> dictMonad_0;
public static final Object lazyApp = (java.util.function.Function<Object, Object>) (dictLazy_0) -> dictLazy_0;
public static final Object hoistLowerApp = Unsafe_Coerce.unsafeCoerce;
public static final Object hoistLiftApp = Unsafe_Coerce.unsafeCoerce;
public static final Object hoistApp = (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (v_1) -> ((java.util.function.Function<Object, Object>) (f_0)).apply(v_1);
public static final Object functorApp = (java.util.function.Function<Object, Object>) (dictFunctor_0) -> dictFunctor_0;
public static final Object extendApp = (java.util.function.Function<Object, Object>) (dictExtend_0) -> dictExtend_0;
public static final Object eqApp = (java.util.function.Function<Object, Object>) (dictEq1_0) -> (java.util.function.Function<Object, Object>) (dictEq_1) -> new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_2) -> (java.util.function.Function<Object, Object>) (y_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq1_0).get("eq1"))).apply(dictEq_1))).apply(x_2))).apply(y_3)); }};
public static final Object ordApp = (java.util.function.Function<Object, Object>) (dictOrd1_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd1_0).get("Eq10"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (dictOrd_2) -> ((new java.util.function.Supplier<Object>() { Object eqApp2_3 = ((new java.util.function.Supplier<Object>() { Object __local_var_3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_2).get("Eq0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("eq", (java.util.function.Function<Object, Object>) (x_4) -> (java.util.function.Function<Object, Object>) (y_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("eq1"))).apply(__local_var_3))).apply(x_4))).apply(y_5)); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (x_4) -> (java.util.function.Function<Object, Object>) (y_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd1_0).get("compare1"))).apply(dictOrd_2))).apply(x_4))).apply(y_5)); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_4) -> eqApp2_3); }}; } })).get(); } })).get();
public static final Object eq1App = (java.util.function.Function<Object, Object>) (dictEq1_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("eq1", (java.util.function.Function<Object, Object>) (dictEq_1) -> (java.util.function.Function<Object, Object>) (x_2) -> (java.util.function.Function<Object, Object>) (y_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq1_0).get("eq1"))).apply(dictEq_1))).apply(x_2))).apply(y_3)); }};
public static final Object ord1App = (java.util.function.Function<Object, Object>) (dictOrd1_0) -> ((new java.util.function.Supplier<Object>() { Object eq1App1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd1_0).get("Eq10"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("eq1", (java.util.function.Function<Object, Object>) (dictEq_2) -> (java.util.function.Function<Object, Object>) (x_3) -> (java.util.function.Function<Object, Object>) (y_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("eq1"))).apply(dictEq_2))).apply(x_3))).apply(y_4)); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compare1", (java.util.function.Function<Object, Object>) (dictOrd_2) -> (java.util.function.Function<Object, Object>) (x_3) -> (java.util.function.Function<Object, Object>) (y_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd1_0).get("compare1"))).apply(dictOrd_2))).apply(x_3))).apply(y_4)); put("Eq10", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> eq1App1_1); }}; } })).get();
public static final Object comonadApp = (java.util.function.Function<Object, Object>) (dictComonad_0) -> dictComonad_0;
public static final Object bindApp = (java.util.function.Function<Object, Object>) (dictBind_0) -> dictBind_0;
public static final Object applyApp = (java.util.function.Function<Object, Object>) (dictApply_0) -> dictApply_0;
public static final Object applicativeApp = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> dictApplicative_0;
public static final Object alternativeApp = (java.util.function.Function<Object, Object>) (dictAlternative_0) -> dictAlternative_0;
public static final Object altApp = (java.util.function.Function<Object, Object>) (dictAlt_0) -> dictAlt_0;
}
