public class Data_Bounded_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object genericTopNoArguments = new java.util.LinkedHashMap<String, Object>() {{ put("genericTop'", new Data_Generic_Rep.NoArguments()); }};
public static final Object genericTopArgument = (java.util.function.Function<Object, Object>) (dictBounded_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericTop'", ((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("top")); }};
public static final Object genericTopprime = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("genericTop'");
public static final Object genericTopConstructor = (java.util.function.Function<Object, Object>) (dictGenericTop_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericTop'", ((java.util.LinkedHashMap<String, Object>) dictGenericTop_0).get("genericTop'")); }};
public static final Object genericTopProduct = (java.util.function.Function<Object, Object>) (dictGenericTop_0) -> (java.util.function.Function<Object, Object>) (dictGenericTop1_1) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericTop'", new Data_Generic_Rep.Product(((java.util.LinkedHashMap<String, Object>) dictGenericTop_0).get("genericTop'"), ((java.util.LinkedHashMap<String, Object>) dictGenericTop1_1).get("genericTop'"))); }};
public static final Object genericTopSum = (java.util.function.Function<Object, Object>) (dictGenericTop_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericTop'", new Data_Generic_Rep.Inr(((java.util.LinkedHashMap<String, Object>) dictGenericTop_0).get("genericTop'"))); }};
public static final Object genericTop = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> (java.util.function.Function<Object, Object>) (dictGenericTop_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0).get("to"))).apply(((java.util.LinkedHashMap<String, Object>) dictGenericTop_1).get("genericTop'"));
public static final Object genericBottomNoArguments = new java.util.LinkedHashMap<String, Object>() {{ put("genericBottom'", new Data_Generic_Rep.NoArguments()); }};
public static final Object genericBottomArgument = (java.util.function.Function<Object, Object>) (dictBounded_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericBottom'", ((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("bottom")); }};
public static final Object genericBottomprime = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("genericBottom'");
public static final Object genericBottomConstructor = (java.util.function.Function<Object, Object>) (dictGenericBottom_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericBottom'", ((java.util.LinkedHashMap<String, Object>) dictGenericBottom_0).get("genericBottom'")); }};
public static final Object genericBottomProduct = (java.util.function.Function<Object, Object>) (dictGenericBottom_0) -> (java.util.function.Function<Object, Object>) (dictGenericBottom1_1) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericBottom'", new Data_Generic_Rep.Product(((java.util.LinkedHashMap<String, Object>) dictGenericBottom_0).get("genericBottom'"), ((java.util.LinkedHashMap<String, Object>) dictGenericBottom1_1).get("genericBottom'"))); }};
public static final Object genericBottomSum = (java.util.function.Function<Object, Object>) (dictGenericBottom_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericBottom'", new Data_Generic_Rep.Inl(((java.util.LinkedHashMap<String, Object>) dictGenericBottom_0).get("genericBottom'"))); }};
public static final Object genericBottom = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> (java.util.function.Function<Object, Object>) (dictGenericBottom_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0).get("to"))).apply(((java.util.LinkedHashMap<String, Object>) dictGenericBottom_1).get("genericBottom'"));
}
