public class Data_Functor_Flip {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Flip = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showFlip = (java.util.function.Function<Object, Object>) (dictShow_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1) -> (((String) ((((String) ("(Flip ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")")))); }};
public static final Object semigroupoidFlip = (java.util.function.Function<Object, Object>) (dictSemigroupoid_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("compose", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroupoid_0).get("compose"))).apply(v1_2))).apply(v_1)); }};
public static final Object ordFlip = (java.util.function.Function<Object, Object>) (dictOrd_0) -> dictOrd_0;
public static final Object newtypeFlip = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object functorFlip = (java.util.function.Function<Object, Object>) (dictBifunctor_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBifunctor_0).get("bimap"))).apply(f_1))).apply((java.util.function.Function<Object, Object>) (x_3) -> x_3))).apply(v_2)); }};
public static final Object eqFlip = (java.util.function.Function<Object, Object>) (dictEq_0) -> dictEq_0;
public static final Object contravariantFlip = (java.util.function.Function<Object, Object>) (dictProfunctor_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("cmap", (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictProfunctor_0).get("dimap"))).apply(f_1))).apply((java.util.function.Function<Object, Object>) (x_3) -> x_3))).apply(v_2)); }};
public static final Object categoryFlip = (java.util.function.Function<Object, Object>) (dictCategory_0) -> ((new java.util.function.Supplier<Object>() { Object semigroupoidFlip1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictCategory_0).get("Semigroupoid0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compose", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("compose"))).apply(v1_3))).apply(v_2)); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("identity", ((java.util.LinkedHashMap<String, Object>) dictCategory_0).get("identity")); put("Semigroupoid0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> semigroupoidFlip1_1); }}; } })).get();
public static final Object bifunctorFlip = (java.util.function.Function<Object, Object>) (dictBifunctor_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (g_2) -> (java.util.function.Function<Object, Object>) (v_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBifunctor_0).get("bimap"))).apply(g_2))).apply(f_1))).apply(v_3)); }};
public static final Object biapplyFlip = (java.util.function.Function<Object, Object>) (dictBiapply_0) -> ((new java.util.function.Supplier<Object>() { Object bifunctorFlip1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (g_3) -> (java.util.function.Function<Object, Object>) (v_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("bimap"))).apply(g_3))).apply(f_2))).apply(v_4)); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("biapply", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapply_0).get("biapply"))).apply(v_2))).apply(v1_3)); put("Bifunctor0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> bifunctorFlip1_1); }}; } })).get();
public static final Object biapplicativeFlip = (java.util.function.Function<Object, Object>) (dictBiapplicative_0) -> ((new java.util.function.Supplier<Object>() { Object biapplyFlip1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapplicative_0).get("Biapply0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((new java.util.function.Supplier<Object>() { Object bifunctorFlip1_2 = ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("Bifunctor0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("bimap", (java.util.function.Function<Object, Object>) (f_3) -> (java.util.function.Function<Object, Object>) (g_4) -> (java.util.function.Function<Object, Object>) (v_5) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("bimap"))).apply(g_4))).apply(f_3))).apply(v_5)); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("biapply", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (v1_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("biapply"))).apply(v_3))).apply(v1_4)); put("Bifunctor0", (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> bifunctorFlip1_2); }}; } })).get(); } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("bipure", (java.util.function.Function<Object, Object>) (a_2) -> (java.util.function.Function<Object, Object>) (b_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBiapplicative_0).get("bipure"))).apply(b_3))).apply(a_2)); put("Biapply0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> biapplyFlip1_1); }}; } })).get();
}
