public class Data_Functor_Product_Nested {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object product9 = (java.util.function.Function<Object, Object>) (a_0) -> (java.util.function.Function<Object, Object>) (b_1) -> (java.util.function.Function<Object, Object>) (c_2) -> (java.util.function.Function<Object, Object>) (d_3) -> (java.util.function.Function<Object, Object>) (e_4) -> (java.util.function.Function<Object, Object>) (f_5) -> (java.util.function.Function<Object, Object>) (g_6) -> (java.util.function.Function<Object, Object>) (h_7) -> (java.util.function.Function<Object, Object>) (i_8) -> new Data_Tuple.Tuple(a_0, new Data_Tuple.Tuple(b_1, new Data_Tuple.Tuple(c_2, new Data_Tuple.Tuple(d_3, new Data_Tuple.Tuple(e_4, new Data_Tuple.Tuple(f_5, new Data_Tuple.Tuple(g_6, new Data_Tuple.Tuple(h_7, new Data_Tuple.Tuple(i_8, Data_Unit.unit)))))))));
public static final Object product8 = (java.util.function.Function<Object, Object>) (a_0) -> (java.util.function.Function<Object, Object>) (b_1) -> (java.util.function.Function<Object, Object>) (c_2) -> (java.util.function.Function<Object, Object>) (d_3) -> (java.util.function.Function<Object, Object>) (e_4) -> (java.util.function.Function<Object, Object>) (f_5) -> (java.util.function.Function<Object, Object>) (g_6) -> (java.util.function.Function<Object, Object>) (h_7) -> new Data_Tuple.Tuple(a_0, new Data_Tuple.Tuple(b_1, new Data_Tuple.Tuple(c_2, new Data_Tuple.Tuple(d_3, new Data_Tuple.Tuple(e_4, new Data_Tuple.Tuple(f_5, new Data_Tuple.Tuple(g_6, new Data_Tuple.Tuple(h_7, Data_Unit.unit))))))));
public static final Object product7 = (java.util.function.Function<Object, Object>) (a_0) -> (java.util.function.Function<Object, Object>) (b_1) -> (java.util.function.Function<Object, Object>) (c_2) -> (java.util.function.Function<Object, Object>) (d_3) -> (java.util.function.Function<Object, Object>) (e_4) -> (java.util.function.Function<Object, Object>) (f_5) -> (java.util.function.Function<Object, Object>) (g_6) -> new Data_Tuple.Tuple(a_0, new Data_Tuple.Tuple(b_1, new Data_Tuple.Tuple(c_2, new Data_Tuple.Tuple(d_3, new Data_Tuple.Tuple(e_4, new Data_Tuple.Tuple(f_5, new Data_Tuple.Tuple(g_6, Data_Unit.unit)))))));
public static final Object product6 = (java.util.function.Function<Object, Object>) (a_0) -> (java.util.function.Function<Object, Object>) (b_1) -> (java.util.function.Function<Object, Object>) (c_2) -> (java.util.function.Function<Object, Object>) (d_3) -> (java.util.function.Function<Object, Object>) (e_4) -> (java.util.function.Function<Object, Object>) (f_5) -> new Data_Tuple.Tuple(a_0, new Data_Tuple.Tuple(b_1, new Data_Tuple.Tuple(c_2, new Data_Tuple.Tuple(d_3, new Data_Tuple.Tuple(e_4, new Data_Tuple.Tuple(f_5, Data_Unit.unit))))));
public static final Object product5 = (java.util.function.Function<Object, Object>) (a_0) -> (java.util.function.Function<Object, Object>) (b_1) -> (java.util.function.Function<Object, Object>) (c_2) -> (java.util.function.Function<Object, Object>) (d_3) -> (java.util.function.Function<Object, Object>) (e_4) -> new Data_Tuple.Tuple(a_0, new Data_Tuple.Tuple(b_1, new Data_Tuple.Tuple(c_2, new Data_Tuple.Tuple(d_3, new Data_Tuple.Tuple(e_4, Data_Unit.unit)))));
public static final Object product4 = (java.util.function.Function<Object, Object>) (a_0) -> (java.util.function.Function<Object, Object>) (b_1) -> (java.util.function.Function<Object, Object>) (c_2) -> (java.util.function.Function<Object, Object>) (d_3) -> new Data_Tuple.Tuple(a_0, new Data_Tuple.Tuple(b_1, new Data_Tuple.Tuple(c_2, new Data_Tuple.Tuple(d_3, Data_Unit.unit))));
public static final Object product3 = (java.util.function.Function<Object, Object>) (a_0) -> (java.util.function.Function<Object, Object>) (b_1) -> (java.util.function.Function<Object, Object>) (c_2) -> new Data_Tuple.Tuple(a_0, new Data_Tuple.Tuple(b_1, new Data_Tuple.Tuple(c_2, Data_Unit.unit)));
public static final Object product2 = (java.util.function.Function<Object, Object>) (a_0) -> (java.util.function.Function<Object, Object>) (b_1) -> new Data_Tuple.Tuple(a_0, new Data_Tuple.Tuple(b_1, Data_Unit.unit));
public static final Object product10 = (java.util.function.Function<Object, Object>) (a_0) -> (java.util.function.Function<Object, Object>) (b_1) -> (java.util.function.Function<Object, Object>) (c_2) -> (java.util.function.Function<Object, Object>) (d_3) -> (java.util.function.Function<Object, Object>) (e_4) -> (java.util.function.Function<Object, Object>) (f_5) -> (java.util.function.Function<Object, Object>) (g_6) -> (java.util.function.Function<Object, Object>) (h_7) -> (java.util.function.Function<Object, Object>) (i_8) -> (java.util.function.Function<Object, Object>) (j_9) -> new Data_Tuple.Tuple(a_0, new Data_Tuple.Tuple(b_1, new Data_Tuple.Tuple(c_2, new Data_Tuple.Tuple(d_3, new Data_Tuple.Tuple(e_4, new Data_Tuple.Tuple(f_5, new Data_Tuple.Tuple(g_6, new Data_Tuple.Tuple(h_7, new Data_Tuple.Tuple(i_8, new Data_Tuple.Tuple(j_9, Data_Unit.unit))))))))));
public static final Object product1 = (java.util.function.Function<Object, Object>) (a_0) -> new Data_Tuple.Tuple(a_0, Data_Unit.unit);
public static final Object get9 = (java.util.function.Function<Object, Object>) (v_0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value0);
public static final Object get8 = (java.util.function.Function<Object, Object>) (v_0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value0);
public static final Object get7 = (java.util.function.Function<Object, Object>) (v_0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0).value1)).value1)).value1)).value1)).value1)).value1)).value0);
public static final Object get6 = (java.util.function.Function<Object, Object>) (v_0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0).value1)).value1)).value1)).value1)).value1)).value0);
public static final Object get5 = (java.util.function.Function<Object, Object>) (v_0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0).value1)).value1)).value1)).value1)).value0);
public static final Object get4 = (java.util.function.Function<Object, Object>) (v_0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0).value1)).value1)).value1)).value0);
public static final Object get3 = (java.util.function.Function<Object, Object>) (v_0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0).value1)).value1)).value0);
public static final Object get2 = (java.util.function.Function<Object, Object>) (v_0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0).value1)).value0);
public static final Object get10 = (java.util.function.Function<Object, Object>) (v_0) -> (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) (((Data_Tuple.Tuple) v_0).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value1)).value0);
public static final Object get1 = (java.util.function.Function<Object, Object>) (v_0) -> (((Data_Tuple.Tuple) v_0).value0);
}
