public class Data_Ord_Min {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Min = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showMin = (java.util.function.Function<Object, Object>) (dictShow_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1) -> (((String) ((((String) ("(Min ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")")))); }};
public static final Object semigroupMin = (java.util.function.Function<Object, Object>) (dictOrd_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((new java.util.function.Supplier<Object>() { Object v_3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(v_1))).apply(v1_2); public Object get() { return ( ((Boolean) ((v_3 instanceof Data_Ordering.LT))) ? v_1 : ( ((Boolean) ((v_3 instanceof Data_Ordering.EQ))) ? v_1 : ( ((Boolean) ((v_3 instanceof Data_Ordering.GT))) ? v1_2 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); } })).get()); }};
public static final Object newtypeMin = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object monoidMin = (java.util.function.Function<Object, Object>) (dictBounded_0) -> ((new java.util.function.Supplier<Object>() { Object semigroupMin1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("Ord0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> ((new java.util.function.Supplier<Object>() { Object v_4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("compare"))).apply(v_2))).apply(v1_3); public Object get() { return ( ((Boolean) ((v_4 instanceof Data_Ordering.LT))) ? v_2 : ( ((Boolean) ((v_4 instanceof Data_Ordering.EQ))) ? v_2 : ( ((Boolean) ((v_4 instanceof Data_Ordering.GT))) ? v1_3 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); } })).get()); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", ((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("top")); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> semigroupMin1_1); }}; } })).get();
public static final Object eqMin = (java.util.function.Function<Object, Object>) (dictEq_0) -> dictEq_0;
public static final Object ordMin = (java.util.function.Function<Object, Object>) (dictOrd_0) -> ((new java.util.function.Supplier<Object>() { Object eqMin1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(v_2))).apply(v1_3)); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> eqMin1_1); }}; } })).get();
}
