public class Data_BooleanAlgebra {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object booleanAlgebraUnit = new java.util.LinkedHashMap<String, Object>() {{ put("HeytingAlgebra0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_HeytingAlgebra.heytingAlgebraUnit); }};
public static final Object booleanAlgebraRecordNil = new java.util.LinkedHashMap<String, Object>() {{ put("HeytingAlgebraRecord0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_HeytingAlgebra.heytingAlgebraRecordNil); }};
public static final Object booleanAlgebraRecordCons = (java.util.function.Function<Object, Object>) (dictIsSymbol_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (dictBooleanAlgebraRecord_2) -> ((new java.util.function.Supplier<Object>() { Object heytingAlgebraRecordCons1_3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_HeytingAlgebra.heytingAlgebraRecordCons)).apply(dictIsSymbol_0))).apply(null /* TODO: PrimUndefined */))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBooleanAlgebraRecord_2).get("HeytingAlgebraRecord0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return (java.util.function.Function<Object, Object>) (dictBooleanAlgebra_4) -> ((new java.util.function.Supplier<Object>() { Object heytingAlgebraRecordCons2_5 = ((java.util.function.Function<Object, Object>) (heytingAlgebraRecordCons1_3)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBooleanAlgebra_4).get("HeytingAlgebra0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("HeytingAlgebraRecord0", (java.util.function.Function<Object, Object>) (_dollar___unused_6) -> heytingAlgebraRecordCons2_5); }}; } })).get(); } })).get();
public static final Object booleanAlgebraRecord = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (dictBooleanAlgebraRecord_1) -> ((new java.util.function.Supplier<Object>() { Object heytingAlgebraRecord1_2 = ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBooleanAlgebraRecord_1).get("HeytingAlgebraRecord0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("ff", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("ffRecord"))).apply(new Type_Proxy.Proxy()))).apply(new Type_Proxy.Proxy())); put("tt", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("ttRecord"))).apply(new Type_Proxy.Proxy()))).apply(new Type_Proxy.Proxy())); put("conj", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("conjRecord"))).apply(new Type_Proxy.Proxy())); put("disj", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("disjRecord"))).apply(new Type_Proxy.Proxy())); put("implies", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("impliesRecord"))).apply(new Type_Proxy.Proxy())); put("not", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("notRecord"))).apply(new Type_Proxy.Proxy())); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("HeytingAlgebra0", (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> heytingAlgebraRecord1_2); }}; } })).get();
public static final Object booleanAlgebraProxy = new java.util.LinkedHashMap<String, Object>() {{ put("HeytingAlgebra0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_HeytingAlgebra.heytingAlgebraProxy); }};
public static final Object booleanAlgebraFn = (java.util.function.Function<Object, Object>) (dictBooleanAlgebra_0) -> ((new java.util.function.Supplier<Object>() { Object heytingAlgebraFunction_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBooleanAlgebra_0).get("HeytingAlgebra0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("ff", (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.LinkedHashMap<String, Object>) __local_var_1).get("ff")); put("tt", (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.LinkedHashMap<String, Object>) __local_var_1).get("tt")); put("implies", (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (g_3) -> (java.util.function.Function<Object, Object>) (a_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("implies"))).apply(((java.util.function.Function<Object, Object>) (f_2)).apply(a_4)))).apply(((java.util.function.Function<Object, Object>) (g_3)).apply(a_4))); put("conj", (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (g_3) -> (java.util.function.Function<Object, Object>) (a_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("conj"))).apply(((java.util.function.Function<Object, Object>) (f_2)).apply(a_4)))).apply(((java.util.function.Function<Object, Object>) (g_3)).apply(a_4))); put("disj", (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (g_3) -> (java.util.function.Function<Object, Object>) (a_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("disj"))).apply(((java.util.function.Function<Object, Object>) (f_2)).apply(a_4)))).apply(((java.util.function.Function<Object, Object>) (g_3)).apply(a_4))); put("not", (java.util.function.Function<Object, Object>) (f_2) -> (java.util.function.Function<Object, Object>) (a_3) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("not"))).apply(((java.util.function.Function<Object, Object>) (f_2)).apply(a_3))); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("HeytingAlgebra0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> heytingAlgebraFunction_1); }}; } })).get();
public static final Object booleanAlgebraBoolean = new java.util.LinkedHashMap<String, Object>() {{ put("HeytingAlgebra0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_HeytingAlgebra.heytingAlgebraBoolean); }};
}
