public class Data_Newtype {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object wrap = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Unsafe_Coerce.unsafeCoerce;
public static final Object unwrap = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Unsafe_Coerce.unsafeCoerce;
public static final Object underF2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> (java.util.function.Function<Object, Object>) (v_4) -> Unsafe_Coerce.unsafeCoerce;
public static final Object underF = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> (java.util.function.Function<Object, Object>) (v_4) -> Unsafe_Coerce.unsafeCoerce;
public static final Object under2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (v_2) -> Unsafe_Coerce.unsafeCoerce;
public static final Object under = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (v_2) -> Unsafe_Coerce.unsafeCoerce;
public static final Object un = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (v_1) -> Unsafe_Coerce.unsafeCoerce;
public static final Object traverse = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (v_2) -> Unsafe_Coerce.unsafeCoerce;
public static final Object overF2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> (java.util.function.Function<Object, Object>) (v_4) -> Unsafe_Coerce.unsafeCoerce;
public static final Object overF = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> (java.util.function.Function<Object, Object>) (v_4) -> Unsafe_Coerce.unsafeCoerce;
public static final Object over2 = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (v_2) -> Unsafe_Coerce.unsafeCoerce;
public static final Object over = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (v_2) -> Unsafe_Coerce.unsafeCoerce;
public static final Object newtypeMultiplicative = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object newtypeLast = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object newtypeFirst = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object newtypeEndo = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object newtypeDual = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object newtypeDisj = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object newtypeConj = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object newtypeAdditive = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object modify = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (fn_1) -> (java.util.function.Function<Object, Object>) (t_2) -> ((java.util.function.Function<Object, Object>) (fn_1)).apply(t_2);
public static final Object collect = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (v_2) -> Unsafe_Coerce.unsafeCoerce;
public static final Object alaF = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> (java.util.function.Function<Object, Object>) (v_4) -> Unsafe_Coerce.unsafeCoerce;
public static final Object ala = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (_dollar___unused_1) -> (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (f_4) -> ((java.util.function.Function<Object, Object>) (f_4)).apply(Unsafe_Coerce.unsafeCoerce);
}
