public class Data_Ord {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    // FFI provided by ../javapurs-prelude/src/Data/Ord.java
    public static Object unsafeCompareImpl = (java.util.function.Function<Object, Object>) (lt) -> (java.util.function.Function<Object, Object>) (eq) -> (java.util.function.Function<Object, Object>) (gt) -> (java.util.function.Function<Object, Object>) (x) -> (java.util.function.Function<Object, Object>) (y) -> {
        int cmp;
        if (x instanceof String && y instanceof String) {
            cmp = ((String) x).compareTo((String) y);
        } else if (x instanceof Integer && y instanceof Integer) {
            cmp = ((Integer) x).compareTo((Integer) y);
        } else if (x instanceof Double && y instanceof Double) {
            cmp = ((Double) x).compareTo((Double) y);
        } else if (x instanceof Boolean && y instanceof Boolean) {
            cmp = ((Boolean) x).compareTo((Boolean) y);
        } else {
            throw new RuntimeException("unsafeCompareImpl: Unsupported types " + x.getClass() + " and " + y.getClass());
        }
        if (cmp < 0) return lt;
        if (cmp > 0) return gt;
        return eq;
    };

    public static Object ordBooleanImpl = unsafeCompareImpl;
    public static Object ordIntImpl = unsafeCompareImpl;
    public static Object ordNumberImpl = unsafeCompareImpl;
    public static Object ordStringImpl = unsafeCompareImpl;
    public static Object ordCharImpl = unsafeCompareImpl;

    public static Object ordArrayImpl = (java.util.function.Function<Object, Object>) (f) -> (java.util.function.Function<Object, Object>) (xs) -> (java.util.function.Function<Object, Object>) (ys) -> {
        Object[] arr1 = (Object[]) xs;
        Object[] arr2 = (Object[]) ys;
        int xlen = arr1.length;
        int ylen = arr2.length;
        int i = 0;
        while (i < xlen && i < ylen) {
            Object x = arr1[i];
            Object y = arr2[i];
            int o = (Integer) ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) f).apply(x)).apply(y);
            if (o != 0) {
                return o;
            }
            i++;
        }
        if (xlen == ylen) {
            return 0;
        } else if (xlen > ylen) {
            return -1;
        } else {
            return 1;
        }
    };


public static final Object ordVoid = new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> new Data_Ordering.EQ()); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Eq.eqVoid); }};
public static final Object ordUnit = new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> new Data_Ordering.EQ()); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Eq.eqUnit); }};
public static final Object ordString = new java.util.LinkedHashMap<String, Object>() {{ put("compare", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordStringImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT())); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Eq.eqString); }};
public static final Object ordRecordNil = new java.util.LinkedHashMap<String, Object>() {{ put("compareRecord", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> (java.util.function.Function<Object, Object>) (v2_2) -> new Data_Ordering.EQ()); put("EqRecord0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Eq.eqRowNil); }};
public static final Object ordProxy = new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> new Data_Ordering.EQ()); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Eq.eqProxy); }};
public static final Object ordOrdering = new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ( ((Boolean) ((v_0 instanceof Data_Ordering.LT))) ? ( ((Boolean) ((v1_1 instanceof Data_Ordering.LT))) ? new Data_Ordering.EQ() : new Data_Ordering.LT()) : ( ((Boolean) ((v_0 instanceof Data_Ordering.EQ))) ? ( ((Boolean) ((v1_1 instanceof Data_Ordering.EQ))) ? new Data_Ordering.EQ() : ( ((Boolean) ((v1_1 instanceof Data_Ordering.LT))) ? new Data_Ordering.GT() : ( ((Boolean) ((v1_1 instanceof Data_Ordering.GT))) ? new Data_Ordering.LT() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))) : ( ((Boolean) ((v_0 instanceof Data_Ordering.GT))) ? ( ((Boolean) ((v1_1 instanceof Data_Ordering.GT))) ? new Data_Ordering.EQ() : new Data_Ordering.GT()) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Ordering.eqOrdering); }};
public static final Object ordNumber = new java.util.LinkedHashMap<String, Object>() {{ put("compare", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordNumberImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT())); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Eq.eqNumber); }};
public static final Object ordInt = new java.util.LinkedHashMap<String, Object>() {{ put("compare", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT())); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Eq.eqInt); }};
public static final Object ordChar = new java.util.LinkedHashMap<String, Object>() {{ put("compare", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordCharImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT())); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Eq.eqChar); }};
public static final Object ordBoolean = new java.util.LinkedHashMap<String, Object>() {{ put("compare", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordBooleanImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT())); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Eq.eqBoolean); }};
public static final Object compareRecord = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("compareRecord");
public static final Object ordRecord = (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> (java.util.function.Function<Object, Object>) (dictOrdRecord_1) -> ((new java.util.function.Supplier<Object>() { Object eqRec1_2 = new java.util.LinkedHashMap<String, Object>() {{ put("eq", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrdRecord_1).get("EqRecord0"))).apply(null /* TODO: PrimUndefined */)).get("eqRecord"))).apply(new Type_Proxy.Proxy())); }}; public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compare", ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrdRecord_1).get("compareRecord"))).apply(new Type_Proxy.Proxy())); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> eqRec1_2); }}; } })).get();
public static final Object compare1 = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("compare1");
public static final Object compare = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("compare");
public static final Object comparing = (java.util.function.Function<Object, Object>) (dictOrd_0) -> (java.util.function.Function<Object, Object>) (f_1) -> (java.util.function.Function<Object, Object>) (x_2) -> (java.util.function.Function<Object, Object>) (y_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(((java.util.function.Function<Object, Object>) (f_1)).apply(x_2)))).apply(((java.util.function.Function<Object, Object>) (f_1)).apply(y_3));
public static final Object greaterThan = (java.util.function.Function<Object, Object>) (dictOrd_0) -> (java.util.function.Function<Object, Object>) (a1_1) -> (java.util.function.Function<Object, Object>) (a2_2) -> (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(a1_1))).apply(a2_2) instanceof Data_Ordering.GT);
public static final Object greaterThanOrEq = (java.util.function.Function<Object, Object>) (dictOrd_0) -> (java.util.function.Function<Object, Object>) (a1_1) -> (java.util.function.Function<Object, Object>) (a2_2) -> !(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(a1_1))).apply(a2_2) instanceof Data_Ordering.LT))));
public static final Object lessThan = (java.util.function.Function<Object, Object>) (dictOrd_0) -> (java.util.function.Function<Object, Object>) (a1_1) -> (java.util.function.Function<Object, Object>) (a2_2) -> (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(a1_1))).apply(a2_2) instanceof Data_Ordering.LT);
public static final Object signum = (java.util.function.Function<Object, Object>) (dictOrd_0) -> (java.util.function.Function<Object, Object>) (dictRing_1) -> ((new java.util.function.Supplier<Object>() { Object Semiring0_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((new java.util.function.Supplier<Object>() { Object zero_3 = ((java.util.LinkedHashMap<String, Object>) Semiring0_2).get("zero"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object Semiring01_4 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((new java.util.function.Supplier<Object>() { Object one_5 = ((java.util.LinkedHashMap<String, Object>) Semiring0_2).get("one"); public Object get() { return (java.util.function.Function<Object, Object>) (x_6) -> ( ((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(x_6))).apply(zero_3) instanceof Data_Ordering.LT))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_1).get("sub"))).apply(((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("zero")))).apply(((java.util.LinkedHashMap<String, Object>) Semiring01_4).get("one")) : ( ((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(x_6))).apply(zero_3) instanceof Data_Ordering.GT))) ? one_5 : x_6)); } })).get(); } })).get(); } })).get(); } })).get();
public static final Object lessThanOrEq = (java.util.function.Function<Object, Object>) (dictOrd_0) -> (java.util.function.Function<Object, Object>) (a1_1) -> (java.util.function.Function<Object, Object>) (a2_2) -> !(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(a1_1))).apply(a2_2) instanceof Data_Ordering.GT))));
public static final Object max = (java.util.function.Function<Object, Object>) (dictOrd_0) -> (java.util.function.Function<Object, Object>) (x_1) -> (java.util.function.Function<Object, Object>) (y_2) -> ((new java.util.function.Supplier<Object>() { Object v_3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(x_1))).apply(y_2); public Object get() { return ( ((Boolean) ((v_3 instanceof Data_Ordering.LT))) ? y_2 : ( ((Boolean) ((v_3 instanceof Data_Ordering.EQ))) ? x_1 : ( ((Boolean) ((v_3 instanceof Data_Ordering.GT))) ? x_1 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); } })).get();
public static final Object min = (java.util.function.Function<Object, Object>) (dictOrd_0) -> (java.util.function.Function<Object, Object>) (x_1) -> (java.util.function.Function<Object, Object>) (y_2) -> ((new java.util.function.Supplier<Object>() { Object v_3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(x_1))).apply(y_2); public Object get() { return ( ((Boolean) ((v_3 instanceof Data_Ordering.LT))) ? x_1 : ( ((Boolean) ((v_3 instanceof Data_Ordering.EQ))) ? x_1 : ( ((Boolean) ((v_3 instanceof Data_Ordering.GT))) ? y_2 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); } })).get();
public static final Object ordArray = (java.util.function.Function<Object, Object>) (dictOrd_0) -> ((new java.util.function.Supplier<Object>() { Object eqArray_1 = new java.util.LinkedHashMap<String, Object>() {{ put("eq", ((java.util.function.Function<Object, Object>) (Data_Eq.eqArrayImpl)).apply(((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */)).get("eq"))); }}; public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (xs_2) -> (java.util.function.Function<Object, Object>) (ys_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordArrayImpl)).apply((java.util.function.Function<Object, Object>) (x_4) -> (java.util.function.Function<Object, Object>) (y_5) -> ((new java.util.function.Supplier<Object>() { Object v_6 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(x_4))).apply(y_5); public Object get() { return ( ((Boolean) ((v_6 instanceof Data_Ordering.EQ))) ? 0 : ( ((Boolean) ((v_6 instanceof Data_Ordering.LT))) ? 1 : ( ((Boolean) ((v_6 instanceof Data_Ordering.GT))) ? -1 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); } })).get()))).apply(xs_2))).apply(ys_3))); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> eqArray_1); }}; } })).get();
public static final Object ord1Array = new java.util.LinkedHashMap<String, Object>() {{ put("compare1", (java.util.function.Function<Object, Object>) (dictOrd_0) -> (java.util.function.Function<Object, Object>) (xs_1) -> (java.util.function.Function<Object, Object>) (ys_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordArrayImpl)).apply((java.util.function.Function<Object, Object>) (x_3) -> (java.util.function.Function<Object, Object>) (y_4) -> ((new java.util.function.Supplier<Object>() { Object v_5 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(x_3))).apply(y_4); public Object get() { return ( ((Boolean) ((v_5 instanceof Data_Ordering.EQ))) ? 0 : ( ((Boolean) ((v_5 instanceof Data_Ordering.LT))) ? 1 : ( ((Boolean) ((v_5 instanceof Data_Ordering.GT))) ? -1 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); } })).get()))).apply(xs_1))).apply(ys_2))); put("Eq10", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Eq.eq1Array); }};
public static final Object ordRecordCons = (java.util.function.Function<Object, Object>) (dictOrdRecord_0) -> ((new java.util.function.Supplier<Object>() { Object eqRowCons_1 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Eq.eqRowCons)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrdRecord_0).get("EqRecord0"))).apply(null /* TODO: PrimUndefined */)))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> (java.util.function.Function<Object, Object>) (dictIsSymbol_3) -> ((new java.util.function.Supplier<Object>() { Object eqRowCons1_4 = ((java.util.function.Function<Object, Object>) (eqRowCons_1)).apply(dictIsSymbol_3); public Object get() { return (java.util.function.Function<Object, Object>) (dictOrd_5) -> ((new java.util.function.Supplier<Object>() { Object eqRowCons2_6 = ((java.util.function.Function<Object, Object>) (eqRowCons1_4)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_5).get("Eq0"))).apply(null /* TODO: PrimUndefined */)); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compareRecord", (java.util.function.Function<Object, Object>) (v_7) -> (java.util.function.Function<Object, Object>) (ra_8) -> (java.util.function.Function<Object, Object>) (rb_9) -> ((new java.util.function.Supplier<Object>() { Object key_10 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictIsSymbol_3).get("reflectSymbol"))).apply(new Type_Proxy.Proxy()); public Object get() { return ((new java.util.function.Supplier<Object>() { Object left_11 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_5).get("compare"))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(key_10))).apply(ra_8)))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Record_Unsafe.unsafeGet)).apply(key_10))).apply(rb_9)); public Object get() { return ( ((Boolean) (!(((Boolean) ((left_11 instanceof Data_Ordering.EQ)))))) ? left_11 : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrdRecord_0).get("compareRecord"))).apply(new Type_Proxy.Proxy()))).apply(ra_8))).apply(rb_9)); } })).get(); } })).get()); put("EqRecord0", (java.util.function.Function<Object, Object>) (_dollar___unused_7) -> eqRowCons2_6); }}; } })).get(); } })).get(); } })).get();
public static final Object clamp = (java.util.function.Function<Object, Object>) (dictOrd_0) -> (java.util.function.Function<Object, Object>) (low_1) -> (java.util.function.Function<Object, Object>) (hi_2) -> (java.util.function.Function<Object, Object>) (x_3) -> ((new java.util.function.Supplier<Object>() { Object __local_var_4 = ((new java.util.function.Supplier<Object>() { Object v_4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(low_1))).apply(x_3); public Object get() { return ( ((Boolean) ((v_4 instanceof Data_Ordering.LT))) ? x_3 : ( ((Boolean) ((v_4 instanceof Data_Ordering.EQ))) ? low_1 : ( ((Boolean) ((v_4 instanceof Data_Ordering.GT))) ? low_1 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); } })).get(); public Object get() { return ((new java.util.function.Supplier<Object>() { Object v_5 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(hi_2))).apply(__local_var_4); public Object get() { return ( ((Boolean) ((v_5 instanceof Data_Ordering.LT))) ? hi_2 : ( ((Boolean) ((v_5 instanceof Data_Ordering.EQ))) ? hi_2 : ( ((Boolean) ((v_5 instanceof Data_Ordering.GT))) ? __local_var_4 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); } })).get(); } })).get();
public static final Object between = (java.util.function.Function<Object, Object>) (dictOrd_0) -> (java.util.function.Function<Object, Object>) (low_1) -> (java.util.function.Function<Object, Object>) (hi_2) -> (java.util.function.Function<Object, Object>) (x_3) -> ( ((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(x_3))).apply(low_1) instanceof Data_Ordering.LT))) ? false : !(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(x_3))).apply(hi_2) instanceof Data_Ordering.GT)))));
public static final Object abs = (java.util.function.Function<Object, Object>) (dictOrd_0) -> (java.util.function.Function<Object, Object>) (dictRing_1) -> ((new java.util.function.Supplier<Object>() { Object zero_2 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("zero"); public Object get() { return (java.util.function.Function<Object, Object>) (x_3) -> ( ((Boolean) (!(((Boolean) ((((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(x_3))).apply(zero_2) instanceof Data_Ordering.LT)))))) ? x_3 : ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_1).get("sub"))).apply(((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictRing_1).get("Semiring0"))).apply(null /* TODO: PrimUndefined */)).get("zero")))).apply(x_3)); } })).get();
}
