public class Data_Array_ST_Iterator {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final class Iterator {
            public final Object value0;
            public final Object value1;
            public Iterator(Object value0, Object value1) {
                this.value0 = value0;
                this.value1 = value1;
            }
        }
public static final Object Iterator = (java.util.function.Function<Object, Object>) (value0) -> (java.util.function.Function<Object, Object>) (value1) -> new Data_Array_ST_Iterator.Iterator(value0, value1);
public static final Object peek = (java.util.function.Function<Object, Object>) (v_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = (((Data_Array_ST_Iterator.Iterator) v_0).value1); public Object get() { return ((new java.util.function.Supplier<Object>() { Object i_2 = null /* TODO: PrimEffect */; public Object get() { return ((java.util.function.Function<Object, Object>) ((((Data_Array_ST_Iterator.Iterator) v_0).value0))).apply(i_2); } })).get(); } })).get();
public static final Object next = (java.util.function.Function<Object, Object>) (v_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = (((Data_Array_ST_Iterator.Iterator) v_0).value1); public Object get() { return ((new java.util.function.Supplier<Object>() { Object i_2 = null /* TODO: PrimEffect */; public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_3 = null /* TODO: PrimEffect */; public Object get() { return ((new java.util.function.Supplier<Object>() { Object _dollar___unused_4 = null /* TODO: PrimEffect */; public Object get() { return ((java.util.function.Function<Object, Object>) ((((Data_Array_ST_Iterator.Iterator) v_0).value0))).apply(i_2); } })).get(); } })).get(); } })).get(); } })).get();
public static final Object pushWhile = (java.util.function.Function<Object, Object>) (p_0) -> (java.util.function.Function<Object, Object>) (iter_1) -> (java.util.function.Function<Object, Object>) (array_2) -> ((new java.util.function.Supplier<Object>() { Object go__break_3 = null /* TODO: PrimEffect */; public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Monad_ST_Internal.$while)).apply(((new java.util.function.Supplier<Object>() { Object __local_var_4 = null /* TODO: PrimEffect */; public Object get() { return !(((Boolean) (__local_var_4))); } })).get()))).apply(((new java.util.function.Supplier<Object>() { Object __local_var_4 = (((Data_Array_ST_Iterator.Iterator) iter_1).value1); public Object get() { return ((new java.util.function.Supplier<Object>() { Object mx_5 = ((new java.util.function.Supplier<Object>() { Object i_5 = null /* TODO: PrimEffect */; public Object get() { return ((java.util.function.Function<Object, Object>) ((((Data_Array_ST_Iterator.Iterator) iter_1).value0))).apply(i_5); } })).get(); public Object get() { return ( ((Boolean) ((((Boolean) ((mx_5 instanceof Data_Maybe.Just))) && ((Boolean) (((java.util.function.Function<Object, Object>) (p_0)).apply((((Data_Maybe.Just) mx_5).value0))))))) ? ((new java.util.function.Supplier<Object>() { Object _dollar___unused_6 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array_ST.pushImpl)).apply((((Data_Maybe.Just) mx_5).value0)))).apply(array_2); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_7 = ((new java.util.function.Supplier<Object>() { Object i_7 = null /* TODO: PrimEffect */; public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_8 = null /* TODO: PrimEffect */; public Object get() { return ((new java.util.function.Supplier<Object>() { Object _dollar___unused_9 = null /* TODO: PrimEffect */; public Object get() { return ((java.util.function.Function<Object, Object>) ((((Data_Array_ST_Iterator.Iterator) iter_1).value0))).apply(i_7); } })).get(); } })).get(); } })).get(); public Object get() { return Data_Unit.unit; } })).get(); } })).get() : ((new java.util.function.Supplier<Object>() { Object __local_var_6 = null /* TODO: PrimEffect */; public Object get() { return Data_Unit.unit; } })).get()); } })).get(); } })).get()); } })).get();
public static final Object pushAll = ((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.pushWhile)).apply((java.util.function.Function<Object, Object>) (v_0) -> true);
public static final Object iterator = (java.util.function.Function<Object, Object>) (f_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (Data_Array_ST_Iterator.Iterator)).apply(f_0); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_2 = null /* TODO: PrimEffect */; public Object get() { return ((java.util.function.Function<Object, Object>) (__local_var_1)).apply(__local_var_2); } })).get(); } })).get();
public static final Object iterate = (java.util.function.Function<Object, Object>) (iter_0) -> (java.util.function.Function<Object, Object>) (f_1) -> ((new java.util.function.Supplier<Object>() { Object go__break_2 = null /* TODO: PrimEffect */; public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Control_Monad_ST_Internal.$while)).apply(((new java.util.function.Supplier<Object>() { Object __local_var_3 = null /* TODO: PrimEffect */; public Object get() { return !(((Boolean) (__local_var_3))); } })).get()))).apply(((new java.util.function.Supplier<Object>() { Object __local_var_3 = (((Data_Array_ST_Iterator.Iterator) iter_0).value1); public Object get() { return ((new java.util.function.Supplier<Object>() { Object mx_4 = ((new java.util.function.Supplier<Object>() { Object i_4 = null /* TODO: PrimEffect */; public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_5 = null /* TODO: PrimEffect */; public Object get() { return ((new java.util.function.Supplier<Object>() { Object _dollar___unused_6 = null /* TODO: PrimEffect */; public Object get() { return ((java.util.function.Function<Object, Object>) ((((Data_Array_ST_Iterator.Iterator) iter_0).value0))).apply(i_4); } })).get(); } })).get(); } })).get(); public Object get() { return ( ((Boolean) ((mx_4 instanceof Data_Maybe.Just))) ? ((java.util.function.Function<Object, Object>) (f_1)).apply((((Data_Maybe.Just) mx_4).value0)) : ( ((Boolean) ((mx_4 instanceof Data_Maybe.Nothing))) ? ((new java.util.function.Supplier<Object>() { Object __local_var_5 = null /* TODO: PrimEffect */; public Object get() { return Data_Unit.unit; } })).get() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); } })).get(); } })).get()); } })).get();
public static final Object exhausted = (java.util.function.Function<Object, Object>) (x_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = (((Data_Array_ST_Iterator.Iterator) x_0).value1); public Object get() { return ((new java.util.function.Supplier<Object>() { Object i_2 = null /* TODO: PrimEffect */; public Object get() { return ((java.util.function.Function<Object, Object>) ((((Data_Array_ST_Iterator.Iterator) x_0).value0))).apply(i_2); } })).get(); } })).get(); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_2 = __local_var_1; public Object get() { return ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Nothing))) ? true : ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Just))) ? false : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); } })).get(); } })).get();
}
