public class Data_Monoid_Dual {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Dual = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showDual = (java.util.function.Function<Object, Object>) (dictShow_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1) -> (((String) ((((String) ("(Dual ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")")))); }};
public static final Object semigroupDual = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append"))).apply(v1_2))).apply(v_1)); }};
public static final Object ordDual = (java.util.function.Function<Object, Object>) (dictOrd_0) -> dictOrd_0;
public static final Object monoidDual = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object semigroupDual1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("append"))).apply(v1_3))).apply(v_2)); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", ((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("mempty")); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> semigroupDual1_1); }}; } })).get();
public static final Object functorDual = new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (m_1) -> ((java.util.function.Function<Object, Object>) (f_0)).apply(m_1)); }};
public static final Object eqDual = (java.util.function.Function<Object, Object>) (dictEq_0) -> dictEq_0;
public static final Object eq1Dual = new java.util.LinkedHashMap<String, Object>() {{ put("eq1", (java.util.function.Function<Object, Object>) (dictEq_0) -> ((java.util.LinkedHashMap<String, Object>) dictEq_0).get("eq")); }};
public static final Object ord1Dual = new java.util.LinkedHashMap<String, Object>() {{ put("compare1", (java.util.function.Function<Object, Object>) (dictOrd_0) -> ((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare")); put("Eq10", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Dual.eq1Dual); }};
public static final Object boundedDual = (java.util.function.Function<Object, Object>) (dictBounded_0) -> dictBounded_0;
public static final Object applyDual = new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> ((java.util.function.Function<Object, Object>) (v_0)).apply(v1_1)); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Dual.functorDual); }};
public static final Object bindDual = new java.util.LinkedHashMap<String, Object>() {{ put("bind", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (f_1) -> ((java.util.function.Function<Object, Object>) (f_1)).apply(v_0)); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Dual.applyDual); }};
public static final Object applicativeDual = new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (x_0) -> x_0); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Dual.applyDual); }};
public static final Object monadDual = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Dual.applicativeDual); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Monoid_Dual.bindDual); }};
}
