public class Data_Ord_Down {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object Down = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object showDown = (java.util.function.Function<Object, Object>) (dictShow_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_1) -> (((String) ((((String) ("(Down ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))).apply(v_1)))))) + ((String) (")")))); }};
public static final Object newtypeDown = new java.util.LinkedHashMap<String, Object>() {{ put("Coercible0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> null /* TODO: PrimUndefined */); }};
public static final Object eqDown = (java.util.function.Function<Object, Object>) (dictEq_0) -> dictEq_0;
public static final Object ordDown = (java.util.function.Function<Object, Object>) (dictOrd_0) -> ((new java.util.function.Supplier<Object>() { Object eqDown1_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> ((new java.util.function.Supplier<Object>() { Object __local_var_4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(v_2))).apply(v1_3); public Object get() { return ( ((Boolean) ((__local_var_4 instanceof Data_Ordering.GT))) ? new Data_Ordering.LT() : ( ((Boolean) ((__local_var_4 instanceof Data_Ordering.EQ))) ? new Data_Ordering.EQ() : ( ((Boolean) ((__local_var_4 instanceof Data_Ordering.LT))) ? new Data_Ordering.GT() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); } })).get()); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> eqDown1_1); }}; } })).get();
public static final Object boundedDown = (java.util.function.Function<Object, Object>) (dictBounded_0) -> ((new java.util.function.Supplier<Object>() { Object ordDown1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("Ord0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((new java.util.function.Supplier<Object>() { Object eqDown1_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("Eq0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (v_3) -> (java.util.function.Function<Object, Object>) (v1_4) -> ((new java.util.function.Supplier<Object>() { Object __local_var_5 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("compare"))).apply(v_3))).apply(v1_4); public Object get() { return ( ((Boolean) ((__local_var_5 instanceof Data_Ordering.GT))) ? new Data_Ordering.LT() : ( ((Boolean) ((__local_var_5 instanceof Data_Ordering.EQ))) ? new Data_Ordering.EQ() : ( ((Boolean) ((__local_var_5 instanceof Data_Ordering.LT))) ? new Data_Ordering.GT() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); } })).get()); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_3) -> eqDown1_2); }}; } })).get(); } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("top", ((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("bottom")); put("bottom", ((java.util.LinkedHashMap<String, Object>) dictBounded_0).get("top")); put("Ord0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> ordDown1_1); }}; } })).get();
}
