public class Data_Eq_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object genericEqNoConstructors = new java.util.LinkedHashMap<String, Object>() {{ put("genericEq'", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> true); }};
public static final Object genericEqNoArguments = new java.util.LinkedHashMap<String, Object>() {{ put("genericEq'", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> true); }};
public static final Object genericEqArgument = (java.util.function.Function<Object, Object>) (dictEq_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericEq'", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq_0).get("eq"))).apply(v_1))).apply(v1_2)); }};
public static final Object genericEqprime = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("genericEq'");
public static final Object genericEqConstructor = (java.util.function.Function<Object, Object>) (dictGenericEq_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericEq'", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericEq_0).get("genericEq'"))).apply(v_1))).apply(v1_2)); }};
public static final Object genericEqProduct = (java.util.function.Function<Object, Object>) (dictGenericEq_0) -> (java.util.function.Function<Object, Object>) (dictGenericEq1_1) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericEq'", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> (((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericEq_0).get("genericEq'"))).apply((((Data_Generic_Rep.Product) v_2).value0)))).apply((((Data_Generic_Rep.Product) v1_3).value0)))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericEq1_1).get("genericEq'"))).apply((((Data_Generic_Rep.Product) v_2).value1)))).apply((((Data_Generic_Rep.Product) v1_3).value1)))))); }};
public static final Object genericEqSum = (java.util.function.Function<Object, Object>) (dictGenericEq_0) -> (java.util.function.Function<Object, Object>) (dictGenericEq1_1) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericEq'", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> ( ((Boolean) ((v_2 instanceof Data_Generic_Rep.Inl))) ? (((Boolean) ((v1_3 instanceof Data_Generic_Rep.Inl))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericEq_0).get("genericEq'"))).apply((((Data_Generic_Rep.Inl) v_2).value0)))).apply((((Data_Generic_Rep.Inl) v1_3).value0))))) : (((Boolean) ((v_2 instanceof Data_Generic_Rep.Inr))) && ((Boolean) ((((Boolean) ((v1_3 instanceof Data_Generic_Rep.Inr))) && ((Boolean) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericEq1_1).get("genericEq'"))).apply((((Data_Generic_Rep.Inr) v_2).value0)))).apply((((Data_Generic_Rep.Inr) v1_3).value0)))))))))); }};
public static final Object genericEq = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> (java.util.function.Function<Object, Object>) (dictGenericEq_1) -> (java.util.function.Function<Object, Object>) (x_2) -> (java.util.function.Function<Object, Object>) (y_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericEq_1).get("genericEq'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0).get("from"))).apply(x_2)))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0).get("from"))).apply(y_3));
}
