public class Data_Array_NonEmpty_Internal {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object foldl1Impl = FFI_STUB;
    public static Object foldl1Impl(Object... args) { return null; }
    public static Object foldr1Impl = FFI_STUB;
    public static Object foldr1Impl(Object... args) { return null; }
    public static Object traverse1Impl = FFI_STUB;
    public static Object traverse1Impl(Object... args) { return null; }

public static final Object NonEmptyArray = (java.util.function.Function<Object, Object>) (x_0) -> x_0;
public static final Object unfoldable1NonEmptyArray = Data_Unfoldable1.unfoldable1Array;
public static final Object traversableWithIndexNonEmptyArray = Data_TraversableWithIndex.traversableWithIndexArray;
public static final Object traversableNonEmptyArray = Data_Traversable.traversableArray;
public static final Object showNonEmptyArray = (java.util.function.Function<Object, Object>) (dictShow_0) -> ((new java.util.function.Supplier<Object>() { Object showArray_1 = new java.util.LinkedHashMap<String, Object>() {{ put("show", ((java.util.function.Function<Object, Object>) (Data_Show.showArrayImpl)).apply(((java.util.LinkedHashMap<String, Object>) dictShow_0).get("show"))); }}; public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("show", (java.util.function.Function<Object, Object>) (v_2) -> (((String) ((((String) ("(NonEmptyArray ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) showArray_1).get("show"))).apply(v_2)))))) + ((String) (")")))); }}; } })).get();
public static final Object semigroupNonEmptyArray = Data_Semigroup.semigroupArray;
public static final Object ordNonEmptyArray = (java.util.function.Function<Object, Object>) (dictOrd_0) -> ((new java.util.function.Supplier<Object>() { Object eqArray_1 = new java.util.LinkedHashMap<String, Object>() {{ put("eq", ((java.util.function.Function<Object, Object>) (Data_Eq.eqArrayImpl)).apply(((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("Eq0"))).apply(null /* TODO: PrimUndefined */)).get("eq"))); }}; public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("compare", (java.util.function.Function<Object, Object>) (xs_2) -> (java.util.function.Function<Object, Object>) (ys_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordIntImpl)).apply(new Data_Ordering.LT()))).apply(new Data_Ordering.EQ()))).apply(new Data_Ordering.GT()))).apply(0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Ord.ordArrayImpl)).apply((java.util.function.Function<Object, Object>) (x_4) -> (java.util.function.Function<Object, Object>) (y_5) -> ((new java.util.function.Supplier<Object>() { Object v_6 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(x_4))).apply(y_5); public Object get() { return ( ((Boolean) ((v_6 instanceof Data_Ordering.EQ))) ? 0 : ( ((Boolean) ((v_6 instanceof Data_Ordering.LT))) ? 1 : ( ((Boolean) ((v_6 instanceof Data_Ordering.GT))) ? -1 : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); } })).get()))).apply(xs_2))).apply(ys_3))); put("Eq0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> eqArray_1); }}; } })).get();
public static final Object ord1NonEmptyArray = Data_Ord.ord1Array;
public static final Object monadNonEmptyArray = Control_Monad.monadArray;
public static final Object functorWithIndexNonEmptyArray = Data_FunctorWithIndex.functorWithIndexArray;
public static final Object functorNonEmptyArray = Data_Functor.functorArray;
public static final Object foldableWithIndexNonEmptyArray = Data_FoldableWithIndex.foldableWithIndexArray;
public static final Object foldableNonEmptyArray = Data_Foldable.foldableArray;
public static final Object foldable1NonEmptyArray = new java.util.LinkedHashMap<String, Object>() {{ put("foldMap1", (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> ((new java.util.function.Supplier<Object>() { Object append_1 = ((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append"); public Object get() { return (java.util.function.Function<Object, Object>) (f_2) -> ((new java.util.function.Supplier<Object>() { Object __local_var_3 = ((java.util.function.Function<Object, Object>) (Data_Functor.arrayMap)).apply(f_2); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_4 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_Array_NonEmpty_Internal.foldable1NonEmptyArray).get("foldl1"))).apply(append_1); public Object get() { return (java.util.function.Function<Object, Object>) (x_5) -> ((java.util.function.Function<Object, Object>) (__local_var_4)).apply(((java.util.function.Function<Object, Object>) (__local_var_3)).apply(x_5)); } })).get(); } })).get(); } })).get()); put("foldr1", (java.util.function.Function<Object, Object>) (__local_var_0) -> (java.util.function.Function<Object, Object>) (__local_var_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array_NonEmpty_Internal.foldr1Impl)).apply(__local_var_0))).apply(__local_var_1)); put("foldl1", (java.util.function.Function<Object, Object>) (__local_var_0) -> (java.util.function.Function<Object, Object>) (__local_var_1) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array_NonEmpty_Internal.foldl1Impl)).apply(__local_var_0))).apply(__local_var_1)); put("Foldable0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Foldable.foldableArray); }};
public static final Object traversable1NonEmptyArray = new java.util.LinkedHashMap<String, Object>() {{ put("traverse1", (java.util.function.Function<Object, Object>) (dictApply_0) -> ((new java.util.function.Supplier<Object>() { Object apply_1 = ((java.util.LinkedHashMap<String, Object>) dictApply_0).get("apply"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object go__map_2 = ((java.util.LinkedHashMap<String, Object>) ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictApply_0).get("Functor0"))).apply(null /* TODO: PrimUndefined */)).get("map"); public Object get() { return (java.util.function.Function<Object, Object>) (f_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Array_NonEmpty_Internal.traverse1Impl)).apply(apply_1))).apply(go__map_2))).apply(f_3); } })).get(); } })).get()); put("sequence1", (java.util.function.Function<Object, Object>) (dictApply_0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Data_Array_NonEmpty_Internal.traversable1NonEmptyArray).get("traverse1"))).apply(dictApply_0))).apply((java.util.function.Function<Object, Object>) (x_1) -> x_1)); put("Foldable10", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Array_NonEmpty_Internal.foldable1NonEmptyArray); put("Traversable1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Traversable.traversableArray); }};
public static final Object eqNonEmptyArray = (java.util.function.Function<Object, Object>) (dictEq_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("eq", ((java.util.function.Function<Object, Object>) (Data_Eq.eqArrayImpl)).apply(((java.util.LinkedHashMap<String, Object>) dictEq_0).get("eq"))); }};
public static final Object eq1NonEmptyArray = Data_Eq.eq1Array;
public static final Object bindNonEmptyArray = Control_Bind.bindArray;
public static final Object applyNonEmptyArray = Control_Apply.applyArray;
public static final Object applicativeNonEmptyArray = Control_Applicative.applicativeArray;
public static final Object altNonEmptyArray = Control_Alt.altArray;
}
