public class Data_Ord_Generic {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object genericOrdNoConstructors = new java.util.LinkedHashMap<String, Object>() {{ put("genericCompare'", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> new Data_Ordering.EQ()); }};
public static final Object genericOrdNoArguments = new java.util.LinkedHashMap<String, Object>() {{ put("genericCompare'", (java.util.function.Function<Object, Object>) (v_0) -> (java.util.function.Function<Object, Object>) (v1_1) -> new Data_Ordering.EQ()); }};
public static final Object genericOrdArgument = (java.util.function.Function<Object, Object>) (dictOrd_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericCompare'", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictOrd_0).get("compare"))).apply(v_1))).apply(v1_2)); }};
public static final Object genericCompareprime = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("genericCompare'");
public static final Object genericOrdConstructor = (java.util.function.Function<Object, Object>) (dictGenericOrd_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericCompare'", (java.util.function.Function<Object, Object>) (v_1) -> (java.util.function.Function<Object, Object>) (v1_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericOrd_0).get("genericCompare'"))).apply(v_1))).apply(v1_2)); }};
public static final Object genericOrdProduct = (java.util.function.Function<Object, Object>) (dictGenericOrd_0) -> (java.util.function.Function<Object, Object>) (dictGenericOrd1_1) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericCompare'", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> ((new java.util.function.Supplier<Object>() { Object v2_4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericOrd_0).get("genericCompare'"))).apply((((Data_Generic_Rep.Product) v_2).value0)))).apply((((Data_Generic_Rep.Product) v1_3).value0)); public Object get() { return ( ((Boolean) ((v2_4 instanceof Data_Ordering.EQ))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericOrd1_1).get("genericCompare'"))).apply((((Data_Generic_Rep.Product) v_2).value1)))).apply((((Data_Generic_Rep.Product) v1_3).value1)) : v2_4); } })).get()); }};
public static final Object genericOrdSum = (java.util.function.Function<Object, Object>) (dictGenericOrd_0) -> (java.util.function.Function<Object, Object>) (dictGenericOrd1_1) -> new java.util.LinkedHashMap<String, Object>() {{ put("genericCompare'", (java.util.function.Function<Object, Object>) (v_2) -> (java.util.function.Function<Object, Object>) (v1_3) -> ( ((Boolean) ((v_2 instanceof Data_Generic_Rep.Inl))) ? ( ((Boolean) ((v1_3 instanceof Data_Generic_Rep.Inl))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericOrd_0).get("genericCompare'"))).apply((((Data_Generic_Rep.Inl) v_2).value0)))).apply((((Data_Generic_Rep.Inl) v1_3).value0)) : ( ((Boolean) ((v1_3 instanceof Data_Generic_Rep.Inr))) ? new Data_Ordering.LT() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())) : ( ((Boolean) ((v_2 instanceof Data_Generic_Rep.Inr))) ? ( ((Boolean) ((v1_3 instanceof Data_Generic_Rep.Inr))) ? ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericOrd1_1).get("genericCompare'"))).apply((((Data_Generic_Rep.Inr) v_2).value0)))).apply((((Data_Generic_Rep.Inr) v1_3).value0)) : ( ((Boolean) ((v1_3 instanceof Data_Generic_Rep.Inl))) ? new Data_Ordering.GT() : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get()))); }};
public static final Object genericCompare = (java.util.function.Function<Object, Object>) (dictGeneric_0) -> (java.util.function.Function<Object, Object>) (dictGenericOrd_1) -> (java.util.function.Function<Object, Object>) (x_2) -> (java.util.function.Function<Object, Object>) (y_3) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGenericOrd_1).get("genericCompare'"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0).get("from"))).apply(x_2)))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictGeneric_0).get("from"))).apply(y_3));
}
