public class Data_Unfoldable {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object unfoldrArrayImpl = FFI_STUB;
    public static Object unfoldrArrayImpl(Object... args) { return null; }

public static final Object unfoldr = (java.util.function.Function<Object, Object>) (dict_0) -> ((java.util.LinkedHashMap<String, Object>) dict_0).get("unfoldr");
public static final Object unfoldableMaybe = new java.util.LinkedHashMap<String, Object>() {{ put("unfoldr", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (b_1) -> ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) (f_0)).apply(b_1); public Object get() { return ( ((Boolean) ((__local_var_2 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just((((Data_Tuple.Tuple) (((Data_Maybe.Just) __local_var_2).value0)).value0)) : new Data_Maybe.Nothing()); } })).get()); put("Unfoldable10", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Unfoldable1.unfoldable1Maybe); }};
public static final Object unfoldableArray = new java.util.LinkedHashMap<String, Object>() {{ put("unfoldr", ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (Data_Unfoldable.unfoldrArrayImpl)).apply(Data_Maybe.isNothing))).apply((java.util.function.Function<Object, Object>) (v_0) -> ( ((Boolean) ((v_0 instanceof Data_Maybe.Just))) ? (((Data_Maybe.Just) v_0).value0) : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())))).apply(Data_Tuple.fst))).apply(Data_Tuple.snd)); put("Unfoldable10", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Data_Unfoldable1.unfoldable1Array); }};
public static final Object replicate = (java.util.function.Function<Object, Object>) (dictUnfoldable_0) -> (java.util.function.Function<Object, Object>) (n_1) -> (java.util.function.Function<Object, Object>) (v_2) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable_0).get("unfoldr"))).apply((java.util.function.Function<Object, Object>) (i_3) -> ( ((Boolean) ((((Integer) (i_3)) <= ((Integer) (0))))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(new Data_Tuple.Tuple(v_2, (((Integer) (i_3)) - ((Integer) (1))))))))).apply(n_1);
public static final Object replicateA = (java.util.function.Function<Object, Object>) (dictApplicative_0) -> (java.util.function.Function<Object, Object>) (dictUnfoldable_1) -> (java.util.function.Function<Object, Object>) (dictTraversable_2) -> (java.util.function.Function<Object, Object>) (n_3) -> (java.util.function.Function<Object, Object>) (m_4) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictTraversable_2).get("sequence"))).apply(dictApplicative_0))).apply(((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable_1).get("unfoldr"))).apply((java.util.function.Function<Object, Object>) (i_5) -> ( ((Boolean) ((((Integer) (i_5)) <= ((Integer) (0))))) ? new Data_Maybe.Nothing() : new Data_Maybe.Just(new Data_Tuple.Tuple(m_4, (((Integer) (i_5)) - ((Integer) (1))))))))).apply(n_3));
public static final Object none = (java.util.function.Function<Object, Object>) (dictUnfoldable_0) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable_0).get("unfoldr"))).apply((java.util.function.Function<Object, Object>) (v_1) -> new Data_Maybe.Nothing()))).apply(Data_Unit.unit);
public static final Object fromMaybe = (java.util.function.Function<Object, Object>) (dictUnfoldable_0) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictUnfoldable_0).get("unfoldr"))).apply((java.util.function.Function<Object, Object>) (b_1) -> ( ((Boolean) ((b_1 instanceof Data_Maybe.Just))) ? new Data_Maybe.Just(new Data_Tuple.Tuple((((Data_Maybe.Just) b_1).value0), new Data_Maybe.Nothing())) : new Data_Maybe.Nothing()));
}
