public class Effect {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    public static Object bindE = FFI_STUB;
    public static Object bindE(Object... args) { return null; }
    public static Object forE = FFI_STUB;
    public static Object forE(Object... args) { return null; }
    public static Object foreachE = FFI_STUB;
    public static Object foreachE(Object... args) { return null; }
    public static Object pureE = FFI_STUB;
    public static Object pureE(Object... args) { return null; }
    public static Object untilE = FFI_STUB;
    public static Object untilE(Object... args) { return null; }
    public static Object whileE = FFI_STUB;
    public static Object whileE(Object... args) { return null; }

public static final Object monadEffect = new java.util.LinkedHashMap<String, Object>() {{ put("Applicative0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Effect.applicativeEffect); put("Bind1", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Effect.bindEffect); }};
public static final Object bindEffect = new java.util.LinkedHashMap<String, Object>() {{ put("bind", (java.util.function.Function<Object, Object>) (a) -> (java.util.function.Function<Object, Object>) (f) -> (java.util.function.Supplier<Object>) () -> { return ((java.util.function.Supplier<Object>) ((java.util.function.Function<Object, Object>) f).apply(((java.util.function.Supplier<Object>) a).get())).get(); }); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Effect.applyEffect); }};
public static final Object applyEffect = new java.util.LinkedHashMap<String, Object>() {{ put("apply", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (a_1) -> ((new java.util.function.Supplier<Object>() { Object f_prime__2 = f_0; public Object get() { return ((new java.util.function.Supplier<Object>() { Object a_prime__3 = a_1; public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Effect.applicativeEffect).get("pure"))).apply(((java.util.function.Function<Object, Object>) (f_prime__2)).apply(a_prime__3)); } })).get(); } })).get()); put("Functor0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Effect.functorEffect); }};
public static final Object applicativeEffect = new java.util.LinkedHashMap<String, Object>() {{ put("pure", (java.util.function.Function<Object, Object>) (a) -> (java.util.function.Supplier<Object>) () -> a); put("Apply0", (java.util.function.Function<Object, Object>) (_dollar___unused_0) -> Effect.applyEffect); }};
public static final Object functorEffect = new java.util.LinkedHashMap<String, Object>() {{ put("map", (java.util.function.Function<Object, Object>) (f_0) -> (java.util.function.Function<Object, Object>) (a_1) -> ((new java.util.function.Supplier<Object>() { Object a_prime__2 = a_1; public Object get() { return ((java.util.function.Function<Object, Object>) (f_0)).apply(a_prime__2); } })).get()); }};
public static final Object semigroupEffect = (java.util.function.Function<Object, Object>) (dictSemigroup_0) -> new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (a_1) -> (java.util.function.Function<Object, Object>) (b_2) -> ((new java.util.function.Supplier<Object>() { Object f_prime__3 = ((new java.util.function.Supplier<Object>() { Object a_prime__3 = a_1; public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictSemigroup_0).get("append"))).apply(a_prime__3); } })).get(); public Object get() { return ((new java.util.function.Supplier<Object>() { Object a_prime__4 = b_2; public Object get() { return ((java.util.function.Function<Object, Object>) (f_prime__3)).apply(a_prime__4); } })).get(); } })).get()); }};
public static final Object monoidEffect = (java.util.function.Function<Object, Object>) (dictMonoid_0) -> ((new java.util.function.Supplier<Object>() { Object semigroupEffect1_1 = ((new java.util.function.Supplier<Object>() { Object __local_var_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("Semigroup0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("append", (java.util.function.Function<Object, Object>) (a_2) -> (java.util.function.Function<Object, Object>) (b_3) -> ((new java.util.function.Supplier<Object>() { Object f_prime__4 = ((new java.util.function.Supplier<Object>() { Object a_prime__4 = a_2; public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("append"))).apply(a_prime__4); } })).get(); public Object get() { return ((new java.util.function.Supplier<Object>() { Object a_prime__5 = b_3; public Object get() { return ((java.util.function.Function<Object, Object>) (f_prime__4)).apply(a_prime__5); } })).get(); } })).get()); }}; } })).get(); public Object get() { return new java.util.LinkedHashMap<String, Object>() {{ put("mempty", ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.LinkedHashMap<String, Object>) dictMonoid_0).get("mempty"); public Object get() { return __local_var_2; } })).get()); put("Semigroup0", (java.util.function.Function<Object, Object>) (_dollar___unused_2) -> semigroupEffect1_1); }}; } })).get();
}
