public class Effect_Class_Console {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };


public static final Object warnShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> (java.util.function.Function<Object, Object>) (dictShow_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.warn)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_1).get("show"))).apply(x_2)));
public static final Object warn = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> (java.util.function.Function<Object, Object>) (x_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.warn)).apply(x_1));
public static final Object timeLog = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> (java.util.function.Function<Object, Object>) (x_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.timeLog)).apply(x_1));
public static final Object timeEnd = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> (java.util.function.Function<Object, Object>) (x_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.timeEnd)).apply(x_1));
public static final Object time = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> (java.util.function.Function<Object, Object>) (x_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.time)).apply(x_1));
public static final Object logShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> (java.util.function.Function<Object, Object>) (dictShow_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_1).get("show"))).apply(x_2)));
public static final Object log = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> (java.util.function.Function<Object, Object>) (x_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (arg) -> (java.util.function.Supplier<Object>) () -> { System.out.println(arg); return null; })).apply(x_1));
public static final Object infoShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> (java.util.function.Function<Object, Object>) (dictShow_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.info)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_1).get("show"))).apply(x_2)));
public static final Object info = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> (java.util.function.Function<Object, Object>) (x_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.info)).apply(x_1));
public static final Object groupEnd = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(Effect_Console.groupEnd);
public static final Object groupCollapsed = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> (java.util.function.Function<Object, Object>) (x_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.groupCollapsed)).apply(x_1));
public static final Object group = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> (java.util.function.Function<Object, Object>) (x_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.group)).apply(x_1));
public static final Object grouped = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> ((new java.util.function.Supplier<Object>() { Object Monad0_1 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("Monad0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((new java.util.function.Supplier<Object>() { Object Bind1_2 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Monad0_1).get("Bind1"))).apply(null /* TODO: PrimUndefined */); public Object get() { return ((new java.util.function.Supplier<Object>() { Object groupEnd1_3 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(Effect_Console.groupEnd); public Object get() { return ((new java.util.function.Supplier<Object>() { Object Applicative0_4 = ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Monad0_1).get("Applicative0"))).apply(null /* TODO: PrimUndefined */); public Object get() { return (java.util.function.Function<Object, Object>) (name_5) -> (java.util.function.Function<Object, Object>) (inner_6) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_2).get("bind"))).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.group)).apply(name_5))))).apply((java.util.function.Function<Object, Object>) (_dollar___unused_7) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_2).get("bind"))).apply(inner_6))).apply((java.util.function.Function<Object, Object>) (result_8) -> ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Bind1_2).get("bind"))).apply(groupEnd1_3))).apply((java.util.function.Function<Object, Object>) (_dollar___unused_9) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) Applicative0_4).get("pure"))).apply(result_8)))); } })).get(); } })).get(); } })).get(); } })).get();
public static final Object errorShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> (java.util.function.Function<Object, Object>) (dictShow_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.error)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_1).get("show"))).apply(x_2)));
public static final Object error = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> (java.util.function.Function<Object, Object>) (x_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.error)).apply(x_1));
public static final Object debugShow = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> (java.util.function.Function<Object, Object>) (dictShow_1) -> (java.util.function.Function<Object, Object>) (x_2) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.debug)).apply(((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_1).get("show"))).apply(x_2)));
public static final Object debug = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> (java.util.function.Function<Object, Object>) (x_1) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(((java.util.function.Function<Object, Object>) (Effect_Console.debug)).apply(x_1));
public static final Object clear = (java.util.function.Function<Object, Object>) (dictMonadEffect_0) -> ((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictMonadEffect_0).get("liftEffect"))).apply(Effect_Console.clear);
}
