public class Test_Assert {
    public static final Object FFI_STUB = new java.util.function.Function<Object, Object>() {
        public Object apply(Object arg) { return this; }
    };
    // FFI provided by /Users/0x1/Documents/htdocs/javapurs/javapurs-strings-extra/src/Test/Assert.java
    public static Object assertImpl = (java.util.function.Function<Object, Object>) (msg) -> (java.util.function.Function<Object, Object>) (cond) -> (java.util.function.Supplier<Object>) () -> {
        if (!(Boolean) cond) {
            System.err.println("Assertion failed: " + msg);
            throw new RuntimeException("Assertion failed: " + msg);
        }
        return null;
    };
    public static Object checkThrows = (java.util.function.Function<Object, Object>) (fn) -> (java.util.function.Supplier<Object>) () -> {
        try {
            ((java.util.function.Function<Object, Object>) fn).apply(null);
            return false;
        } catch (Exception e) {
            return true;
        }
    };


public static final Object assertprime = (java.util.function.Function<Object, Object>) (msg) -> (java.util.function.Function<Object, Object>) (b) -> (java.util.function.Supplier<Object>) () -> { if (!((Boolean) b)) { throw new RuntimeException((String) msg); } return null; };
public static final Object assertEqualprime = (java.util.function.Function<Object, Object>) (dictEq_0) -> (java.util.function.Function<Object, Object>) (dictShow_1) -> (java.util.function.Function<Object, Object>) (userMessage_2) -> (java.util.function.Function<Object, Object>) (v_3) -> ((new java.util.function.Supplier<Object>() { Object result_4 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq_0).get("eq"))).apply(((java.util.LinkedHashMap<String, Object>) v_3).get("actual")))).apply(((java.util.LinkedHashMap<String, Object>) v_3).get("expected")); public Object get() { return ((new java.util.function.Supplier<Object>() { Object message_5 = (((String) ((((String) ((((String) (( ((Boolean) (java.util.Objects.equals(userMessage_2, ""))) ? (((String) ("")) + ((String) ("Expected: "))) : (((String) (userMessage_2)) + ((String) ("\nExpected: ")))))) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_1).get("show"))).apply(((java.util.LinkedHashMap<String, Object>) v_3).get("expected"))))))) + ((String) ("\nActual:   "))))) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_1).get("show"))).apply(((java.util.LinkedHashMap<String, Object>) v_3).get("actual"))))); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_6 = ((java.util.function.Function<Object, Object>) (Effect_Console.error)).apply(message_5); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_7 = ( ((Boolean) (!(((Boolean) (result_4))))) ? __local_var_6 : ( ((Boolean) (result_4)) ? Data_Unit.unit : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); public Object get() { return ((new java.util.function.Supplier<Object>() { Object _dollar___unused_8 = __local_var_7; public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (msg) -> (java.util.function.Function<Object, Object>) (b) -> (java.util.function.Supplier<Object>) () -> { if (!((Boolean) b)) { throw new RuntimeException((String) msg); } return null; })).apply(message_5))).apply(result_4); } })).get(); } })).get(); } })).get(); } })).get(); } })).get();
public static final Object assertEqual = (java.util.function.Function<Object, Object>) (dictEq_0) -> (java.util.function.Function<Object, Object>) (dictShow_1) -> (java.util.function.Function<Object, Object>) (v_2) -> ((new java.util.function.Supplier<Object>() { Object result_3 = ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictEq_0).get("eq"))).apply(((java.util.LinkedHashMap<String, Object>) v_2).get("actual")))).apply(((java.util.LinkedHashMap<String, Object>) v_2).get("expected")); public Object get() { return ((new java.util.function.Supplier<Object>() { Object message_4 = (((String) ((((String) ((((String) ("Expected: ")) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_1).get("show"))).apply(((java.util.LinkedHashMap<String, Object>) v_2).get("expected"))))))) + ((String) ("\nActual:   "))))) + ((String) (((java.util.function.Function<Object, Object>) (((java.util.LinkedHashMap<String, Object>) dictShow_1).get("show"))).apply(((java.util.LinkedHashMap<String, Object>) v_2).get("actual"))))); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_5 = ((java.util.function.Function<Object, Object>) (Effect_Console.error)).apply(message_4); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_6 = ( ((Boolean) (!(((Boolean) (result_3))))) ? __local_var_5 : ( ((Boolean) (result_3)) ? Data_Unit.unit : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); public Object get() { return ((new java.util.function.Supplier<Object>() { Object _dollar___unused_7 = __local_var_6; public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (msg) -> (java.util.function.Function<Object, Object>) (b) -> (java.util.function.Supplier<Object>) () -> { if (!((Boolean) b)) { throw new RuntimeException((String) msg); } return null; })).apply(message_4))).apply(result_3); } })).get(); } })).get(); } })).get(); } })).get(); } })).get();
public static final Object assertFalse = (java.util.function.Function<Object, Object>) (actual_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = new java.util.LinkedHashMap<String, Object>() {{ put("actual", actual_0); put("expected", false); }}; public Object get() { return ((new java.util.function.Supplier<Object>() { Object result_2 = !(((Boolean) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("actual")))); public Object get() { return ((new java.util.function.Supplier<Object>() { Object message_3 = ( ((Boolean) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("actual"))) ? (((String) ("Expected: false\nActual:   ")) + ((String) ("true"))) : (((String) ("Expected: false\nActual:   ")) + ((String) ("false")))); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_4 = ((java.util.function.Function<Object, Object>) (Effect_Console.error)).apply(message_3); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_5 = ( ((Boolean) (!(((Boolean) (result_2))))) ? __local_var_4 : ( ((Boolean) (result_2)) ? Data_Unit.unit : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); public Object get() { return ((new java.util.function.Supplier<Object>() { Object _dollar___unused_6 = __local_var_5; public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (msg) -> (java.util.function.Function<Object, Object>) (b) -> (java.util.function.Supplier<Object>) () -> { if (!((Boolean) b)) { throw new RuntimeException((String) msg); } return null; })).apply(message_3))).apply(result_2); } })).get(); } })).get(); } })).get(); } })).get(); } })).get(); } })).get();
public static final Object assertTrue = (java.util.function.Function<Object, Object>) (actual_0) -> ((new java.util.function.Supplier<Object>() { Object __local_var_1 = new java.util.LinkedHashMap<String, Object>() {{ put("actual", actual_0); put("expected", true); }}; public Object get() { return ((new java.util.function.Supplier<Object>() { Object result_2 = ((java.util.LinkedHashMap<String, Object>) __local_var_1).get("actual"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object message_3 = ( ((Boolean) (((java.util.LinkedHashMap<String, Object>) __local_var_1).get("actual"))) ? (((String) ("Expected: true\nActual:   ")) + ((String) ("true"))) : (((String) ("Expected: true\nActual:   ")) + ((String) ("false")))); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_4 = ((java.util.function.Function<Object, Object>) (Effect_Console.error)).apply(message_3); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_5 = ( ((Boolean) (!(((Boolean) (result_2))))) ? __local_var_4 : ( ((Boolean) (result_2)) ? Data_Unit.unit : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); public Object get() { return ((new java.util.function.Supplier<Object>() { Object _dollar___unused_6 = __local_var_5; public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (msg) -> (java.util.function.Function<Object, Object>) (b) -> (java.util.function.Supplier<Object>) () -> { if (!((Boolean) b)) { throw new RuntimeException((String) msg); } return null; })).apply(message_3))).apply(result_2); } })).get(); } })).get(); } })).get(); } })).get(); } })).get(); } })).get();
public static final Object assertFalseprime = (java.util.function.Function<Object, Object>) (message_0) -> (java.util.function.Function<Object, Object>) (actual_1) -> ((new java.util.function.Supplier<Object>() { Object __local_var_2 = new java.util.LinkedHashMap<String, Object>() {{ put("actual", actual_1); put("expected", false); }}; public Object get() { return ((new java.util.function.Supplier<Object>() { Object result_3 = !(((Boolean) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("actual")))); public Object get() { return ((new java.util.function.Supplier<Object>() { Object message_4 = (((String) (( ((Boolean) (java.util.Objects.equals(message_0, ""))) ? "Expected: false\nActual:   " : (((String) (message_0)) + ((String) ("\nExpected: false\nActual:   ")))))) + ((String) (( ((Boolean) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("actual"))) ? "true" : "false")))); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_5 = ((java.util.function.Function<Object, Object>) (Effect_Console.error)).apply(message_4); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_6 = ( ((Boolean) (!(((Boolean) (result_3))))) ? __local_var_5 : ( ((Boolean) (result_3)) ? Data_Unit.unit : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); public Object get() { return ((new java.util.function.Supplier<Object>() { Object _dollar___unused_7 = __local_var_6; public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (msg) -> (java.util.function.Function<Object, Object>) (b) -> (java.util.function.Supplier<Object>) () -> { if (!((Boolean) b)) { throw new RuntimeException((String) msg); } return null; })).apply(message_4))).apply(result_3); } })).get(); } })).get(); } })).get(); } })).get(); } })).get(); } })).get();
public static final Object assertTrueprime = (java.util.function.Function<Object, Object>) (message_0) -> (java.util.function.Function<Object, Object>) (actual_1) -> ((new java.util.function.Supplier<Object>() { Object __local_var_2 = new java.util.LinkedHashMap<String, Object>() {{ put("actual", actual_1); put("expected", true); }}; public Object get() { return ((new java.util.function.Supplier<Object>() { Object result_3 = ((java.util.LinkedHashMap<String, Object>) __local_var_2).get("actual"); public Object get() { return ((new java.util.function.Supplier<Object>() { Object message_4 = (((String) (( ((Boolean) (java.util.Objects.equals(message_0, ""))) ? "Expected: true\nActual:   " : (((String) (message_0)) + ((String) ("\nExpected: true\nActual:   ")))))) + ((String) (( ((Boolean) (((java.util.LinkedHashMap<String, Object>) __local_var_2).get("actual"))) ? "true" : "false")))); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_5 = ((java.util.function.Function<Object, Object>) (Effect_Console.error)).apply(message_4); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_6 = ( ((Boolean) (!(((Boolean) (result_3))))) ? __local_var_5 : ( ((Boolean) (result_3)) ? Data_Unit.unit : ((java.util.function.Supplier<Object>) () -> { throw new RuntimeException("Failed pattern match"); }).get())); public Object get() { return ((new java.util.function.Supplier<Object>() { Object _dollar___unused_7 = __local_var_6; public Object get() { return ((java.util.function.Function<Object, Object>) (((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (msg) -> (java.util.function.Function<Object, Object>) (b) -> (java.util.function.Supplier<Object>) () -> { if (!((Boolean) b)) { throw new RuntimeException((String) msg); } return null; })).apply(message_4))).apply(result_3); } })).get(); } })).get(); } })).get(); } })).get(); } })).get(); } })).get();
public static final Object assertThrowsprime = (java.util.function.Function<Object, Object>) (msg_0) -> (java.util.function.Function<Object, Object>) (fn_1) -> ((new java.util.function.Supplier<Object>() { Object __local_var_2 = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (msg) -> (java.util.function.Function<Object, Object>) (b) -> (java.util.function.Supplier<Object>) () -> { if (!((Boolean) b)) { throw new RuntimeException((String) msg); } return null; })).apply(msg_0); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_3 = ((java.util.function.Function<Object, Object>) (Test_Assert.checkThrows)).apply(fn_1); public Object get() { return ((new java.util.function.Supplier<Object>() { Object __local_var_4 = __local_var_3; public Object get() { return ((java.util.function.Function<Object, Object>) (__local_var_2)).apply(__local_var_4); } })).get(); } })).get(); } })).get();
public static final Object assertThrows = ((java.util.function.Function<Object, Object>) (Test_Assert.assertThrowsprime)).apply("Assertion failed: An error should have been thrown");
public static final Object $assert = ((java.util.function.Function<Object, Object>) ((java.util.function.Function<Object, Object>) (msg) -> (java.util.function.Function<Object, Object>) (b) -> (java.util.function.Supplier<Object>) () -> { if (!((Boolean) b)) { throw new RuntimeException((String) msg); } return null; })).apply("Assertion failed");
}
